// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/blog.proto

package therapistpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlogStatus int32

const (
	BlogStatus_BLOG_STATUS_UNSPECIFIED BlogStatus = 0
	BlogStatus_BLOG_STATUS_DRAFT       BlogStatus = 1
	BlogStatus_BLOG_STATUS_PUBLISHED   BlogStatus = 2
)

// Enum value maps for BlogStatus.
var (
	BlogStatus_name = map[int32]string{
		0: "BLOG_STATUS_UNSPECIFIED",
		1: "BLOG_STATUS_DRAFT",
		2: "BLOG_STATUS_PUBLISHED",
	}
	BlogStatus_value = map[string]int32{
		"BLOG_STATUS_UNSPECIFIED": 0,
		"BLOG_STATUS_DRAFT":       1,
		"BLOG_STATUS_PUBLISHED":   2,
	}
)

func (x BlogStatus) Enum() *BlogStatus {
	p := new(BlogStatus)
	*p = x
	return p
}

func (x BlogStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlogStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_blog_proto_enumTypes[0].Descriptor()
}

func (BlogStatus) Type() protoreflect.EnumType {
	return &file_proto_blog_proto_enumTypes[0]
}

func (x BlogStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlogStatus.Descriptor instead.
func (BlogStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{0}
}

type Blog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TherapistId   string                 `protobuf:"bytes,2,opt,name=therapist_id,json=therapistId,proto3" json:"therapist_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	CoverImageUrl string                 `protobuf:"bytes,5,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                      // plain text / markdown, max 50 000 chars
	ImageUrls     []string               `protobuf:"bytes,7,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"` // max 2 inline images
	Status        BlogStatus             `protobuf:"varint,8,opt,name=status,proto3,enum=therapist.BlogStatus" json:"status,omitempty"`
	Views         int64                  `protobuf:"varint,9,opt,name=views,proto3" json:"views,omitempty"`
	Likes         int64                  `protobuf:"varint,10,opt,name=likes,proto3" json:"likes,omitempty"`
	LikedByMe     bool                   `protobuf:"varint,11,opt,name=liked_by_me,json=likedByMe,proto3" json:"liked_by_me,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,14,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	Tags          []string               `protobuf:"bytes,15,rep,name=tags,proto3" json:"tags,omitempty"` // e.g. ["anxiety","depression","stress"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blog) Reset() {
	*x = Blog{}
	mi := &file_proto_blog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog) ProtoMessage() {}

func (x *Blog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog.ProtoReflect.Descriptor instead.
func (*Blog) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{0}
}

func (x *Blog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Blog) GetTherapistId() string {
	if x != nil {
		return x.TherapistId
	}
	return ""
}

func (x *Blog) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Blog) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Blog) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *Blog) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Blog) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *Blog) GetStatus() BlogStatus {
	if x != nil {
		return x.Status
	}
	return BlogStatus_BLOG_STATUS_UNSPECIFIED
}

func (x *Blog) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *Blog) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *Blog) GetLikedByMe() bool {
	if x != nil {
		return x.LikedByMe
	}
	return false
}

func (x *Blog) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Blog) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Blog) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *Blog) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// CreateBlog — verified therapists only; creates a draft.
type CreateBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TherapistId   string                 `protobuf:"bytes,1,opt,name=therapist_id,json=therapistId,proto3" json:"therapist_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CoverImageUrl string                 `protobuf:"bytes,4,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,5,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBlogRequest) Reset() {
	*x = CreateBlogRequest{}
	mi := &file_proto_blog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogRequest) ProtoMessage() {}

func (x *CreateBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogRequest.ProtoReflect.Descriptor instead.
func (*CreateBlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBlogRequest) GetTherapistId() string {
	if x != nil {
		return x.TherapistId
	}
	return ""
}

func (x *CreateBlogRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBlogRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateBlogRequest) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *CreateBlogRequest) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *CreateBlogRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateBlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blog          *Blog                  `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBlogResponse) Reset() {
	*x = CreateBlogResponse{}
	mi := &file_proto_blog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogResponse) ProtoMessage() {}

func (x *CreateBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogResponse.ProtoReflect.Descriptor instead.
func (*CreateBlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBlogResponse) GetBlog() *Blog {
	if x != nil {
		return x.Blog
	}
	return nil
}

// UpdateBlog — own draft only.
type UpdateBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TherapistId   string                 `protobuf:"bytes,1,opt,name=therapist_id,json=therapistId,proto3" json:"therapist_id,omitempty"`
	BlogId        string                 `protobuf:"bytes,2,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CoverImageUrl string                 `protobuf:"bytes,5,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,6,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBlogRequest) Reset() {
	*x = UpdateBlogRequest{}
	mi := &file_proto_blog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlogRequest) ProtoMessage() {}

func (x *UpdateBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlogRequest.ProtoReflect.Descriptor instead.
func (*UpdateBlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateBlogRequest) GetTherapistId() string {
	if x != nil {
		return x.TherapistId
	}
	return ""
}

func (x *UpdateBlogRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *UpdateBlogRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateBlogRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateBlogRequest) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *UpdateBlogRequest) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *UpdateBlogRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type UpdateBlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blog          *Blog                  `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBlogResponse) Reset() {
	*x = UpdateBlogResponse{}
	mi := &file_proto_blog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlogResponse) ProtoMessage() {}

func (x *UpdateBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlogResponse.ProtoReflect.Descriptor instead.
func (*UpdateBlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateBlogResponse) GetBlog() *Blog {
	if x != nil {
		return x.Blog
	}
	return nil
}

// PublishBlog — move draft → published.
type PublishBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TherapistId   string                 `protobuf:"bytes,1,opt,name=therapist_id,json=therapistId,proto3" json:"therapist_id,omitempty"`
	BlogId        string                 `protobuf:"bytes,2,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBlogRequest) Reset() {
	*x = PublishBlogRequest{}
	mi := &file_proto_blog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBlogRequest) ProtoMessage() {}

func (x *PublishBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBlogRequest.ProtoReflect.Descriptor instead.
func (*PublishBlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{5}
}

func (x *PublishBlogRequest) GetTherapistId() string {
	if x != nil {
		return x.TherapistId
	}
	return ""
}

func (x *PublishBlogRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

type PublishBlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blog          *Blog                  `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBlogResponse) Reset() {
	*x = PublishBlogResponse{}
	mi := &file_proto_blog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBlogResponse) ProtoMessage() {}

func (x *PublishBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBlogResponse.ProtoReflect.Descriptor instead.
func (*PublishBlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{6}
}

func (x *PublishBlogResponse) GetBlog() *Blog {
	if x != nil {
		return x.Blog
	}
	return nil
}

// DeleteBlog — own blog (any status).
type DeleteBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TherapistId   string                 `protobuf:"bytes,1,opt,name=therapist_id,json=therapistId,proto3" json:"therapist_id,omitempty"`
	BlogId        string                 `protobuf:"bytes,2,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlogRequest) Reset() {
	*x = DeleteBlogRequest{}
	mi := &file_proto_blog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogRequest) ProtoMessage() {}

func (x *DeleteBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogRequest.ProtoReflect.Descriptor instead.
func (*DeleteBlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBlogRequest) GetTherapistId() string {
	if x != nil {
		return x.TherapistId
	}
	return ""
}

func (x *DeleteBlogRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

type DeleteBlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlogResponse) Reset() {
	*x = DeleteBlogResponse{}
	mi := &file_proto_blog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogResponse) ProtoMessage() {}

func (x *DeleteBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogResponse.ProtoReflect.Descriptor instead.
func (*DeleteBlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteBlogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetBlog — fetch one blog; increments views when published.
type GetBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	ViewerId      string                 `protobuf:"bytes,2,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"` // optional — therapist_id of the viewer, used for liked_by_me
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogRequest) Reset() {
	*x = GetBlogRequest{}
	mi := &file_proto_blog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogRequest) ProtoMessage() {}

func (x *GetBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogRequest.ProtoReflect.Descriptor instead.
func (*GetBlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{9}
}

func (x *GetBlogRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *GetBlogRequest) GetViewerId() string {
	if x != nil {
		return x.ViewerId
	}
	return ""
}

type GetBlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blog          *Blog                  `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogResponse) Reset() {
	*x = GetBlogResponse{}
	mi := &file_proto_blog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogResponse) ProtoMessage() {}

func (x *GetBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogResponse.ProtoReflect.Descriptor instead.
func (*GetBlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{10}
}

func (x *GetBlogResponse) GetBlog() *Blog {
	if x != nil {
		return x.Blog
	}
	return nil
}

// ListBlogs — paginated list of published blogs (optionally filtered by therapist).
type ListBlogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TherapistId   string                 `protobuf:"bytes,1,opt,name=therapist_id,json=therapistId,proto3" json:"therapist_id,omitempty"` // optional filter
	ViewerId      string                 `protobuf:"bytes,2,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"`          // optional — for liked_by_me
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                                 // 1-based
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`         // max 50
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlogsRequest) Reset() {
	*x = ListBlogsRequest{}
	mi := &file_proto_blog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlogsRequest) ProtoMessage() {}

func (x *ListBlogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlogsRequest.ProtoReflect.Descriptor instead.
func (*ListBlogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{11}
}

func (x *ListBlogsRequest) GetTherapistId() string {
	if x != nil {
		return x.TherapistId
	}
	return ""
}

func (x *ListBlogsRequest) GetViewerId() string {
	if x != nil {
		return x.ViewerId
	}
	return ""
}

func (x *ListBlogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBlogsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListBlogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blogs         []*Blog                `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlogsResponse) Reset() {
	*x = ListBlogsResponse{}
	mi := &file_proto_blog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlogsResponse) ProtoMessage() {}

func (x *ListBlogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlogsResponse.ProtoReflect.Descriptor instead.
func (*ListBlogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{12}
}

func (x *ListBlogsResponse) GetBlogs() []*Blog {
	if x != nil {
		return x.Blogs
	}
	return nil
}

func (x *ListBlogsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ListMyBlogs — all blogs (draft + published) for the authenticated therapist.
type ListMyBlogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TherapistId   string                 `protobuf:"bytes,1,opt,name=therapist_id,json=therapistId,proto3" json:"therapist_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // 1-based
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // max 50
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyBlogsRequest) Reset() {
	*x = ListMyBlogsRequest{}
	mi := &file_proto_blog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyBlogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyBlogsRequest) ProtoMessage() {}

func (x *ListMyBlogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyBlogsRequest.ProtoReflect.Descriptor instead.
func (*ListMyBlogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{13}
}

func (x *ListMyBlogsRequest) GetTherapistId() string {
	if x != nil {
		return x.TherapistId
	}
	return ""
}

func (x *ListMyBlogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMyBlogsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListMyBlogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blogs         []*Blog                `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyBlogsResponse) Reset() {
	*x = ListMyBlogsResponse{}
	mi := &file_proto_blog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyBlogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyBlogsResponse) ProtoMessage() {}

func (x *ListMyBlogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyBlogsResponse.ProtoReflect.Descriptor instead.
func (*ListMyBlogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{14}
}

func (x *ListMyBlogsResponse) GetBlogs() []*Blog {
	if x != nil {
		return x.Blogs
	}
	return nil
}

func (x *ListMyBlogsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ToggleLikeBlog — like or unlike a published blog.
type ToggleLikeBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TherapistId   string                 `protobuf:"bytes,1,opt,name=therapist_id,json=therapistId,proto3" json:"therapist_id,omitempty"` // the liker
	BlogId        string                 `protobuf:"bytes,2,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleLikeBlogRequest) Reset() {
	*x = ToggleLikeBlogRequest{}
	mi := &file_proto_blog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleLikeBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleLikeBlogRequest) ProtoMessage() {}

func (x *ToggleLikeBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleLikeBlogRequest.ProtoReflect.Descriptor instead.
func (*ToggleLikeBlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{15}
}

func (x *ToggleLikeBlogRequest) GetTherapistId() string {
	if x != nil {
		return x.TherapistId
	}
	return ""
}

func (x *ToggleLikeBlogRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

type ToggleLikeBlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"`
	Likes         int64                  `protobuf:"varint,2,opt,name=likes,proto3" json:"likes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleLikeBlogResponse) Reset() {
	*x = ToggleLikeBlogResponse{}
	mi := &file_proto_blog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleLikeBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleLikeBlogResponse) ProtoMessage() {}

func (x *ToggleLikeBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleLikeBlogResponse.ProtoReflect.Descriptor instead.
func (*ToggleLikeBlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{16}
}

func (x *ToggleLikeBlogResponse) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *ToggleLikeBlogResponse) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

// UploadBlogImage — upload one inline blog image (max 2 MB).
type UploadBlogImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TherapistId   string                 `protobuf:"bytes,1,opt,name=therapist_id,json=therapistId,proto3" json:"therapist_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // image/jpeg | image/png | image/webp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBlogImageRequest) Reset() {
	*x = UploadBlogImageRequest{}
	mi := &file_proto_blog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBlogImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBlogImageRequest) ProtoMessage() {}

func (x *UploadBlogImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBlogImageRequest.ProtoReflect.Descriptor instead.
func (*UploadBlogImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{17}
}

func (x *UploadBlogImageRequest) GetTherapistId() string {
	if x != nil {
		return x.TherapistId
	}
	return ""
}

func (x *UploadBlogImageRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadBlogImageRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadBlogImageRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type UploadBlogImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBlogImageResponse) Reset() {
	*x = UploadBlogImageResponse{}
	mi := &file_proto_blog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBlogImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBlogImageResponse) ProtoMessage() {}

func (x *UploadBlogImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBlogImageResponse.ProtoReflect.Descriptor instead.
func (*UploadBlogImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{18}
}

func (x *UploadBlogImageResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// UserToggleLikeBlog — like or unlike a published blog (user/client accounts).
type UserToggleLikeBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // the liker (user account)
	BlogId        string                 `protobuf:"bytes,2,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserToggleLikeBlogRequest) Reset() {
	*x = UserToggleLikeBlogRequest{}
	mi := &file_proto_blog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserToggleLikeBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserToggleLikeBlogRequest) ProtoMessage() {}

func (x *UserToggleLikeBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserToggleLikeBlogRequest.ProtoReflect.Descriptor instead.
func (*UserToggleLikeBlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{19}
}

func (x *UserToggleLikeBlogRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserToggleLikeBlogRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

type UserToggleLikeBlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"`
	Likes         int64                  `protobuf:"varint,2,opt,name=likes,proto3" json:"likes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserToggleLikeBlogResponse) Reset() {
	*x = UserToggleLikeBlogResponse{}
	mi := &file_proto_blog_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserToggleLikeBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserToggleLikeBlogResponse) ProtoMessage() {}

func (x *UserToggleLikeBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserToggleLikeBlogResponse.ProtoReflect.Descriptor instead.
func (*UserToggleLikeBlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{20}
}

func (x *UserToggleLikeBlogResponse) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *UserToggleLikeBlogResponse) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

var File_proto_blog_proto protoreflect.FileDescriptor

const file_proto_blog_proto_rawDesc = "" +
	"\n" +
	"\x10proto/blog.proto\x12\ttherapist\"\xb4\x03\n" +
	"\x04Blog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\ftherapist_id\x18\x02 \x01(\tR\vtherapistId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12&\n" +
	"\x0fcover_image_url\x18\x05 \x01(\tR\rcoverImageUrl\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"image_urls\x18\a \x03(\tR\timageUrls\x12-\n" +
	"\x06status\x18\b \x01(\x0e2\x15.therapist.BlogStatusR\x06status\x12\x14\n" +
	"\x05views\x18\t \x01(\x03R\x05views\x12\x14\n" +
	"\x05likes\x18\n" +
	" \x01(\x03R\x05likes\x12\x1e\n" +
	"\vliked_by_me\x18\v \x01(\bR\tlikedByMe\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\x12!\n" +
	"\fpublished_at\x18\x0e \x01(\tR\vpublishedAt\x12\x12\n" +
	"\x04tags\x18\x0f \x03(\tR\x04tags\"\xc1\x01\n" +
	"\x11CreateBlogRequest\x12!\n" +
	"\ftherapist_id\x18\x01 \x01(\tR\vtherapistId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12&\n" +
	"\x0fcover_image_url\x18\x04 \x01(\tR\rcoverImageUrl\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x05 \x03(\tR\timageUrls\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\"9\n" +
	"\x12CreateBlogResponse\x12#\n" +
	"\x04blog\x18\x01 \x01(\v2\x0f.therapist.BlogR\x04blog\"\xda\x01\n" +
	"\x11UpdateBlogRequest\x12!\n" +
	"\ftherapist_id\x18\x01 \x01(\tR\vtherapistId\x12\x17\n" +
	"\ablog_id\x18\x02 \x01(\tR\x06blogId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12&\n" +
	"\x0fcover_image_url\x18\x05 \x01(\tR\rcoverImageUrl\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x06 \x03(\tR\timageUrls\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\"9\n" +
	"\x12UpdateBlogResponse\x12#\n" +
	"\x04blog\x18\x01 \x01(\v2\x0f.therapist.BlogR\x04blog\"P\n" +
	"\x12PublishBlogRequest\x12!\n" +
	"\ftherapist_id\x18\x01 \x01(\tR\vtherapistId\x12\x17\n" +
	"\ablog_id\x18\x02 \x01(\tR\x06blogId\":\n" +
	"\x13PublishBlogResponse\x12#\n" +
	"\x04blog\x18\x01 \x01(\v2\x0f.therapist.BlogR\x04blog\"O\n" +
	"\x11DeleteBlogRequest\x12!\n" +
	"\ftherapist_id\x18\x01 \x01(\tR\vtherapistId\x12\x17\n" +
	"\ablog_id\x18\x02 \x01(\tR\x06blogId\".\n" +
	"\x12DeleteBlogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"F\n" +
	"\x0eGetBlogRequest\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\tR\x06blogId\x12\x1b\n" +
	"\tviewer_id\x18\x02 \x01(\tR\bviewerId\"6\n" +
	"\x0fGetBlogResponse\x12#\n" +
	"\x04blog\x18\x01 \x01(\v2\x0f.therapist.BlogR\x04blog\"\x83\x01\n" +
	"\x10ListBlogsRequest\x12!\n" +
	"\ftherapist_id\x18\x01 \x01(\tR\vtherapistId\x12\x1b\n" +
	"\tviewer_id\x18\x02 \x01(\tR\bviewerId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"P\n" +
	"\x11ListBlogsResponse\x12%\n" +
	"\x05blogs\x18\x01 \x03(\v2\x0f.therapist.BlogR\x05blogs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"h\n" +
	"\x12ListMyBlogsRequest\x12!\n" +
	"\ftherapist_id\x18\x01 \x01(\tR\vtherapistId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"R\n" +
	"\x13ListMyBlogsResponse\x12%\n" +
	"\x05blogs\x18\x01 \x03(\v2\x0f.therapist.BlogR\x05blogs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"S\n" +
	"\x15ToggleLikeBlogRequest\x12!\n" +
	"\ftherapist_id\x18\x01 \x01(\tR\vtherapistId\x12\x17\n" +
	"\ablog_id\x18\x02 \x01(\tR\x06blogId\"D\n" +
	"\x16ToggleLikeBlogResponse\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked\x12\x14\n" +
	"\x05likes\x18\x02 \x01(\x03R\x05likes\"\x8f\x01\n" +
	"\x16UploadBlogImageRequest\x12!\n" +
	"\ftherapist_id\x18\x01 \x01(\tR\vtherapistId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\"+\n" +
	"\x17UploadBlogImageResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"M\n" +
	"\x19UserToggleLikeBlogRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\ablog_id\x18\x02 \x01(\tR\x06blogId\"H\n" +
	"\x1aUserToggleLikeBlogResponse\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked\x12\x14\n" +
	"\x05likes\x18\x02 \x01(\x03R\x05likes*[\n" +
	"\n" +
	"BlogStatus\x12\x1b\n" +
	"\x17BLOG_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11BLOG_STATUS_DRAFT\x10\x01\x12\x19\n" +
	"\x15BLOG_STATUS_PUBLISHED\x10\x02B-Z+therapist/pkg/proto/therapistpb;therapistpbb\x06proto3"

var (
	file_proto_blog_proto_rawDescOnce sync.Once
	file_proto_blog_proto_rawDescData []byte
)

func file_proto_blog_proto_rawDescGZIP() []byte {
	file_proto_blog_proto_rawDescOnce.Do(func() {
		file_proto_blog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_blog_proto_rawDesc), len(file_proto_blog_proto_rawDesc)))
	})
	return file_proto_blog_proto_rawDescData
}

var file_proto_blog_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_blog_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_blog_proto_goTypes = []any{
	(BlogStatus)(0),                    // 0: therapist.BlogStatus
	(*Blog)(nil),                       // 1: therapist.Blog
	(*CreateBlogRequest)(nil),          // 2: therapist.CreateBlogRequest
	(*CreateBlogResponse)(nil),         // 3: therapist.CreateBlogResponse
	(*UpdateBlogRequest)(nil),          // 4: therapist.UpdateBlogRequest
	(*UpdateBlogResponse)(nil),         // 5: therapist.UpdateBlogResponse
	(*PublishBlogRequest)(nil),         // 6: therapist.PublishBlogRequest
	(*PublishBlogResponse)(nil),        // 7: therapist.PublishBlogResponse
	(*DeleteBlogRequest)(nil),          // 8: therapist.DeleteBlogRequest
	(*DeleteBlogResponse)(nil),         // 9: therapist.DeleteBlogResponse
	(*GetBlogRequest)(nil),             // 10: therapist.GetBlogRequest
	(*GetBlogResponse)(nil),            // 11: therapist.GetBlogResponse
	(*ListBlogsRequest)(nil),           // 12: therapist.ListBlogsRequest
	(*ListBlogsResponse)(nil),          // 13: therapist.ListBlogsResponse
	(*ListMyBlogsRequest)(nil),         // 14: therapist.ListMyBlogsRequest
	(*ListMyBlogsResponse)(nil),        // 15: therapist.ListMyBlogsResponse
	(*ToggleLikeBlogRequest)(nil),      // 16: therapist.ToggleLikeBlogRequest
	(*ToggleLikeBlogResponse)(nil),     // 17: therapist.ToggleLikeBlogResponse
	(*UploadBlogImageRequest)(nil),     // 18: therapist.UploadBlogImageRequest
	(*UploadBlogImageResponse)(nil),    // 19: therapist.UploadBlogImageResponse
	(*UserToggleLikeBlogRequest)(nil),  // 20: therapist.UserToggleLikeBlogRequest
	(*UserToggleLikeBlogResponse)(nil), // 21: therapist.UserToggleLikeBlogResponse
}
var file_proto_blog_proto_depIdxs = []int32{
	0, // 0: therapist.Blog.status:type_name -> therapist.BlogStatus
	1, // 1: therapist.CreateBlogResponse.blog:type_name -> therapist.Blog
	1, // 2: therapist.UpdateBlogResponse.blog:type_name -> therapist.Blog
	1, // 3: therapist.PublishBlogResponse.blog:type_name -> therapist.Blog
	1, // 4: therapist.GetBlogResponse.blog:type_name -> therapist.Blog
	1, // 5: therapist.ListBlogsResponse.blogs:type_name -> therapist.Blog
	1, // 6: therapist.ListMyBlogsResponse.blogs:type_name -> therapist.Blog
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_blog_proto_init() }
func file_proto_blog_proto_init() {
	if File_proto_blog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_blog_proto_rawDesc), len(file_proto_blog_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_blog_proto_goTypes,
		DependencyIndexes: file_proto_blog_proto_depIdxs,
		EnumInfos:         file_proto_blog_proto_enumTypes,
		MessageInfos:      file_proto_blog_proto_msgTypes,
	}.Build()
	File_proto_blog_proto = out.File
	file_proto_blog_proto_goTypes = nil
	file_proto_blog_proto_depIdxs = nil
}
