// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/discovery.proto

package therapistpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TherapistCard struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TherapistId     string                 `protobuf:"bytes,1,opt,name=therapist_id,json=therapistId,proto3" json:"therapist_id,omitempty"`
	FullName        string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Bio             string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	ProfilePhoto    string                 `protobuf:"bytes,4,opt,name=profile_photo,json=profilePhoto,proto3" json:"profile_photo,omitempty"`
	Specializations []string               `protobuf:"bytes,5,rep,name=specializations,proto3" json:"specializations,omitempty"`
	SessionFee      float64                `protobuf:"fixed64,6,opt,name=session_fee,json=sessionFee,proto3" json:"session_fee,omitempty"`
	SessionTypes    []string               `protobuf:"bytes,7,rep,name=session_types,json=sessionTypes,proto3" json:"session_types,omitempty"` // "video" | "in_person"
	Rating          float64                `protobuf:"fixed64,8,opt,name=rating,proto3" json:"rating,omitempty"`
	TotalSessions   int32                  `protobuf:"varint,9,opt,name=total_sessions,json=totalSessions,proto3" json:"total_sessions,omitempty"`
	State           string                 `protobuf:"bytes,10,opt,name=state,proto3" json:"state,omitempty"`
	Nation          string                 `protobuf:"bytes,11,opt,name=nation,proto3" json:"nation,omitempty"`
	AddressText     string                 `protobuf:"bytes,12,opt,name=address_text,json=addressText,proto3" json:"address_text,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TherapistCard) Reset() {
	*x = TherapistCard{}
	mi := &file_proto_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TherapistCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TherapistCard) ProtoMessage() {}

func (x *TherapistCard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TherapistCard.ProtoReflect.Descriptor instead.
func (*TherapistCard) Descriptor() ([]byte, []int) {
	return file_proto_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *TherapistCard) GetTherapistId() string {
	if x != nil {
		return x.TherapistId
	}
	return ""
}

func (x *TherapistCard) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *TherapistCard) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *TherapistCard) GetProfilePhoto() string {
	if x != nil {
		return x.ProfilePhoto
	}
	return ""
}

func (x *TherapistCard) GetSpecializations() []string {
	if x != nil {
		return x.Specializations
	}
	return nil
}

func (x *TherapistCard) GetSessionFee() float64 {
	if x != nil {
		return x.SessionFee
	}
	return 0
}

func (x *TherapistCard) GetSessionTypes() []string {
	if x != nil {
		return x.SessionTypes
	}
	return nil
}

func (x *TherapistCard) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *TherapistCard) GetTotalSessions() int32 {
	if x != nil {
		return x.TotalSessions
	}
	return 0
}

func (x *TherapistCard) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TherapistCard) GetNation() string {
	if x != nil {
		return x.Nation
	}
	return ""
}

func (x *TherapistCard) GetAddressText() string {
	if x != nil {
		return x.AddressText
	}
	return ""
}

// SearchTherapists — full-text search across verified therapists.
type SearchTherapistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                                // searched in name / bio / specializations
	SessionType   string                 `protobuf:"bytes,2,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"` // optional: "video" | "in_person"
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTherapistsRequest) Reset() {
	*x = SearchTherapistsRequest{}
	mi := &file_proto_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTherapistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTherapistsRequest) ProtoMessage() {}

func (x *SearchTherapistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTherapistsRequest.ProtoReflect.Descriptor instead.
func (*SearchTherapistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *SearchTherapistsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchTherapistsRequest) GetSessionType() string {
	if x != nil {
		return x.SessionType
	}
	return ""
}

func (x *SearchTherapistsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchTherapistsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchTherapistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Therapists    []*TherapistCard       `protobuf:"bytes,1,rep,name=therapists,proto3" json:"therapists,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTherapistsResponse) Reset() {
	*x = SearchTherapistsResponse{}
	mi := &file_proto_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTherapistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTherapistsResponse) ProtoMessage() {}

func (x *SearchTherapistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTherapistsResponse.ProtoReflect.Descriptor instead.
func (*SearchTherapistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *SearchTherapistsResponse) GetTherapists() []*TherapistCard {
	if x != nil {
		return x.Therapists
	}
	return nil
}

func (x *SearchTherapistsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// GetRecommendedTherapists — location + rating-based recommendations.
type GetRecommendedTherapistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`   // user's state — used for location scoring
	Nation        string                 `protobuf:"bytes,2,opt,name=nation,proto3" json:"nation,omitempty"` // user's nation
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendedTherapistsRequest) Reset() {
	*x = GetRecommendedTherapistsRequest{}
	mi := &file_proto_discovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendedTherapistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendedTherapistsRequest) ProtoMessage() {}

func (x *GetRecommendedTherapistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendedTherapistsRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendedTherapistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_discovery_proto_rawDescGZIP(), []int{3}
}

func (x *GetRecommendedTherapistsRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetRecommendedTherapistsRequest) GetNation() string {
	if x != nil {
		return x.Nation
	}
	return ""
}

func (x *GetRecommendedTherapistsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRecommendedTherapistsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetRecommendedTherapistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Therapists    []*TherapistCard       `protobuf:"bytes,1,rep,name=therapists,proto3" json:"therapists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendedTherapistsResponse) Reset() {
	*x = GetRecommendedTherapistsResponse{}
	mi := &file_proto_discovery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendedTherapistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendedTherapistsResponse) ProtoMessage() {}

func (x *GetRecommendedTherapistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discovery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendedTherapistsResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendedTherapistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_discovery_proto_rawDescGZIP(), []int{4}
}

func (x *GetRecommendedTherapistsResponse) GetTherapists() []*TherapistCard {
	if x != nil {
		return x.Therapists
	}
	return nil
}

// GetTherapistProfile — fetch a single verified therapist's public profile.
type GetTherapistProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TherapistId   string                 `protobuf:"bytes,1,opt,name=therapist_id,json=therapistId,proto3" json:"therapist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTherapistProfileRequest) Reset() {
	*x = GetTherapistProfileRequest{}
	mi := &file_proto_discovery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTherapistProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTherapistProfileRequest) ProtoMessage() {}

func (x *GetTherapistProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discovery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTherapistProfileRequest.ProtoReflect.Descriptor instead.
func (*GetTherapistProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_discovery_proto_rawDescGZIP(), []int{5}
}

func (x *GetTherapistProfileRequest) GetTherapistId() string {
	if x != nil {
		return x.TherapistId
	}
	return ""
}

type GetTherapistProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Therapist     *TherapistCard         `protobuf:"bytes,1,opt,name=therapist,proto3" json:"therapist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTherapistProfileResponse) Reset() {
	*x = GetTherapistProfileResponse{}
	mi := &file_proto_discovery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTherapistProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTherapistProfileResponse) ProtoMessage() {}

func (x *GetTherapistProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_discovery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTherapistProfileResponse.ProtoReflect.Descriptor instead.
func (*GetTherapistProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_discovery_proto_rawDescGZIP(), []int{6}
}

func (x *GetTherapistProfileResponse) GetTherapist() *TherapistCard {
	if x != nil {
		return x.Therapist
	}
	return nil
}

var File_proto_discovery_proto protoreflect.FileDescriptor

const file_proto_discovery_proto_rawDesc = "" +
	"\n" +
	"\x15proto/discovery.proto\x12\ttherapist\"\x86\x03\n" +
	"\rTherapistCard\x12!\n" +
	"\ftherapist_id\x18\x01 \x01(\tR\vtherapistId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\x12#\n" +
	"\rprofile_photo\x18\x04 \x01(\tR\fprofilePhoto\x12(\n" +
	"\x0fspecializations\x18\x05 \x03(\tR\x0fspecializations\x12\x1f\n" +
	"\vsession_fee\x18\x06 \x01(\x01R\n" +
	"sessionFee\x12#\n" +
	"\rsession_types\x18\a \x03(\tR\fsessionTypes\x12\x16\n" +
	"\x06rating\x18\b \x01(\x01R\x06rating\x12%\n" +
	"\x0etotal_sessions\x18\t \x01(\x05R\rtotalSessions\x12\x14\n" +
	"\x05state\x18\n" +
	" \x01(\tR\x05state\x12\x16\n" +
	"\x06nation\x18\v \x01(\tR\x06nation\x12!\n" +
	"\faddress_text\x18\f \x01(\tR\vaddressText\"\x83\x01\n" +
	"\x17SearchTherapistsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12!\n" +
	"\fsession_type\x18\x02 \x01(\tR\vsessionType\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"j\n" +
	"\x18SearchTherapistsResponse\x128\n" +
	"\n" +
	"therapists\x18\x01 \x03(\v2\x18.therapist.TherapistCardR\n" +
	"therapists\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x80\x01\n" +
	"\x1fGetRecommendedTherapistsRequest\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x16\n" +
	"\x06nation\x18\x02 \x01(\tR\x06nation\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\\\n" +
	" GetRecommendedTherapistsResponse\x128\n" +
	"\n" +
	"therapists\x18\x01 \x03(\v2\x18.therapist.TherapistCardR\n" +
	"therapists\"?\n" +
	"\x1aGetTherapistProfileRequest\x12!\n" +
	"\ftherapist_id\x18\x01 \x01(\tR\vtherapistId\"U\n" +
	"\x1bGetTherapistProfileResponse\x126\n" +
	"\ttherapist\x18\x01 \x01(\v2\x18.therapist.TherapistCardR\ttherapistB-Z+therapist/pkg/proto/therapistpb;therapistpbb\x06proto3"

var (
	file_proto_discovery_proto_rawDescOnce sync.Once
	file_proto_discovery_proto_rawDescData []byte
)

func file_proto_discovery_proto_rawDescGZIP() []byte {
	file_proto_discovery_proto_rawDescOnce.Do(func() {
		file_proto_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_discovery_proto_rawDesc), len(file_proto_discovery_proto_rawDesc)))
	})
	return file_proto_discovery_proto_rawDescData
}

var file_proto_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_discovery_proto_goTypes = []any{
	(*TherapistCard)(nil),                    // 0: therapist.TherapistCard
	(*SearchTherapistsRequest)(nil),          // 1: therapist.SearchTherapistsRequest
	(*SearchTherapistsResponse)(nil),         // 2: therapist.SearchTherapistsResponse
	(*GetRecommendedTherapistsRequest)(nil),  // 3: therapist.GetRecommendedTherapistsRequest
	(*GetRecommendedTherapistsResponse)(nil), // 4: therapist.GetRecommendedTherapistsResponse
	(*GetTherapistProfileRequest)(nil),       // 5: therapist.GetTherapistProfileRequest
	(*GetTherapistProfileResponse)(nil),      // 6: therapist.GetTherapistProfileResponse
}
var file_proto_discovery_proto_depIdxs = []int32{
	0, // 0: therapist.SearchTherapistsResponse.therapists:type_name -> therapist.TherapistCard
	0, // 1: therapist.GetRecommendedTherapistsResponse.therapists:type_name -> therapist.TherapistCard
	0, // 2: therapist.GetTherapistProfileResponse.therapist:type_name -> therapist.TherapistCard
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_discovery_proto_init() }
func file_proto_discovery_proto_init() {
	if File_proto_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_discovery_proto_rawDesc), len(file_proto_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_discovery_proto_goTypes,
		DependencyIndexes: file_proto_discovery_proto_depIdxs,
		MessageInfos:      file_proto_discovery_proto_msgTypes,
	}.Build()
	File_proto_discovery_proto = out.File
	file_proto_discovery_proto_goTypes = nil
	file_proto_discovery_proto_depIdxs = nil
}
