// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.3
// source: proto/therapist.proto

package therapistpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SupabaseToken string                 `protobuf:"bytes,1,opt,name=supabase_token,json=supabaseToken,proto3" json:"supabase_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthCallbackRequest) Reset() {
	*x = AuthCallbackRequest{}
	mi := &file_proto_therapist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthCallbackRequest) ProtoMessage() {}

func (x *AuthCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthCallbackRequest.ProtoReflect.Descriptor instead.
func (*AuthCallbackRequest) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{0}
}

func (x *AuthCallbackRequest) GetSupabaseToken() string {
	if x != nil {
		return x.SupabaseToken
	}
	return ""
}

type AuthCallbackResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TherapistId string                 `protobuf:"bytes,1,opt,name=therapist_id,json=therapistId,proto3" json:"therapist_id,omitempty"`
	// "needs_onboarding" | "pending" | "verified" | "rejected"
	Status              string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	OnboardingCompleted bool   `protobuf:"varint,3,opt,name=onboarding_completed,json=onboardingCompleted,proto3" json:"onboarding_completed,omitempty"`
	ReferralId          string `protobuf:"bytes,4,opt,name=referral_id,json=referralId,proto3" json:"referral_id,omitempty"`
	RejectionReason     string `protobuf:"bytes,5,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AuthCallbackResponse) Reset() {
	*x = AuthCallbackResponse{}
	mi := &file_proto_therapist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthCallbackResponse) ProtoMessage() {}

func (x *AuthCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthCallbackResponse.ProtoReflect.Descriptor instead.
func (*AuthCallbackResponse) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{1}
}

func (x *AuthCallbackResponse) GetTherapistId() string {
	if x != nil {
		return x.TherapistId
	}
	return ""
}

func (x *AuthCallbackResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AuthCallbackResponse) GetOnboardingCompleted() bool {
	if x != nil {
		return x.OnboardingCompleted
	}
	return false
}

func (x *AuthCallbackResponse) GetReferralId() string {
	if x != nil {
		return x.ReferralId
	}
	return ""
}

func (x *AuthCallbackResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SupabaseToken string                 `protobuf:"bytes,1,opt,name=supabase_token,json=supabaseToken,proto3" json:"supabase_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_proto_therapist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatusRequest) GetSupabaseToken() string {
	if x != nil {
		return x.SupabaseToken
	}
	return ""
}

type GetStatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TherapistId         string                 `protobuf:"bytes,1,opt,name=therapist_id,json=therapistId,proto3" json:"therapist_id,omitempty"`
	Status              string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	OnboardingCompleted bool                   `protobuf:"varint,3,opt,name=onboarding_completed,json=onboardingCompleted,proto3" json:"onboarding_completed,omitempty"`
	ReferralId          string                 `protobuf:"bytes,4,opt,name=referral_id,json=referralId,proto3" json:"referral_id,omitempty"`
	RejectionReason     string                 `protobuf:"bytes,5,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_proto_therapist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetTherapistId() string {
	if x != nil {
		return x.TherapistId
	}
	return ""
}

func (x *GetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetStatusResponse) GetOnboardingCompleted() bool {
	if x != nil {
		return x.OnboardingCompleted
	}
	return false
}

func (x *GetStatusResponse) GetReferralId() string {
	if x != nil {
		return x.ReferralId
	}
	return ""
}

func (x *GetStatusResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

type CompleteOnboardingRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TherapistId string                 `protobuf:"bytes,1,opt,name=therapist_id,json=therapistId,proto3" json:"therapist_id,omitempty"`
	// Required
	FullName           string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	LanguagesSpoken    []string `protobuf:"bytes,3,rep,name=languages_spoken,json=languagesSpoken,proto3" json:"languages_spoken,omitempty"`
	Specializations    []string `protobuf:"bytes,4,rep,name=specializations,proto3" json:"specializations,omitempty"`
	YearsOfExperience  int32    `protobuf:"varint,5,opt,name=years_of_experience,json=yearsOfExperience,proto3" json:"years_of_experience,omitempty"`
	SessionFee         string   `protobuf:"bytes,6,opt,name=session_fee,json=sessionFee,proto3" json:"session_fee,omitempty"`       // decimal string e.g. "1500.00"
	SessionTypes       []string `protobuf:"bytes,7,rep,name=session_types,json=sessionTypes,proto3" json:"session_types,omitempty"` // "chat" | "audio" | "video"
	DegreeCertificate  string   `protobuf:"bytes,8,opt,name=degree_certificate,json=degreeCertificate,proto3" json:"degree_certificate,omitempty"`
	RegistrationNumber string   `protobuf:"bytes,9,opt,name=registration_number,json=registrationNumber,proto3" json:"registration_number,omitempty"`
	IssuingBody        string   `protobuf:"bytes,10,opt,name=issuing_body,json=issuingBody,proto3" json:"issuing_body,omitempty"`
	// Optional
	Gender        string `protobuf:"bytes,11,opt,name=gender,proto3" json:"gender,omitempty"`
	Bio           string `protobuf:"bytes,12,opt,name=bio,proto3" json:"bio,omitempty"`
	ProfilePhoto  string `protobuf:"bytes,13,opt,name=profile_photo,json=profilePhoto,proto3" json:"profile_photo,omitempty"`
	PhoneNumber   string `protobuf:"bytes,14,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	GovernmentId  string `protobuf:"bytes,15,opt,name=government_id,json=governmentId,proto3" json:"government_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOnboardingRequest) Reset() {
	*x = CompleteOnboardingRequest{}
	mi := &file_proto_therapist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOnboardingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOnboardingRequest) ProtoMessage() {}

func (x *CompleteOnboardingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOnboardingRequest.ProtoReflect.Descriptor instead.
func (*CompleteOnboardingRequest) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteOnboardingRequest) GetTherapistId() string {
	if x != nil {
		return x.TherapistId
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetLanguagesSpoken() []string {
	if x != nil {
		return x.LanguagesSpoken
	}
	return nil
}

func (x *CompleteOnboardingRequest) GetSpecializations() []string {
	if x != nil {
		return x.Specializations
	}
	return nil
}

func (x *CompleteOnboardingRequest) GetYearsOfExperience() int32 {
	if x != nil {
		return x.YearsOfExperience
	}
	return 0
}

func (x *CompleteOnboardingRequest) GetSessionFee() string {
	if x != nil {
		return x.SessionFee
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetSessionTypes() []string {
	if x != nil {
		return x.SessionTypes
	}
	return nil
}

func (x *CompleteOnboardingRequest) GetDegreeCertificate() string {
	if x != nil {
		return x.DegreeCertificate
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetRegistrationNumber() string {
	if x != nil {
		return x.RegistrationNumber
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetIssuingBody() string {
	if x != nil {
		return x.IssuingBody
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetProfilePhoto() string {
	if x != nil {
		return x.ProfilePhoto
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetGovernmentId() string {
	if x != nil {
		return x.GovernmentId
	}
	return ""
}

type CompleteOnboardingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOnboardingResponse) Reset() {
	*x = CompleteOnboardingResponse{}
	mi := &file_proto_therapist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOnboardingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOnboardingResponse) ProtoMessage() {}

func (x *CompleteOnboardingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOnboardingResponse.ProtoReflect.Descriptor instead.
func (*CompleteOnboardingResponse) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteOnboardingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ApproveTherapistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TherapistId   string                 `protobuf:"bytes,1,opt,name=therapist_id,json=therapistId,proto3" json:"therapist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveTherapistRequest) Reset() {
	*x = ApproveTherapistRequest{}
	mi := &file_proto_therapist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveTherapistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveTherapistRequest) ProtoMessage() {}

func (x *ApproveTherapistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveTherapistRequest.ProtoReflect.Descriptor instead.
func (*ApproveTherapistRequest) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{6}
}

func (x *ApproveTherapistRequest) GetTherapistId() string {
	if x != nil {
		return x.TherapistId
	}
	return ""
}

type ApproveTherapistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReferralId    string                 `protobuf:"bytes,1,opt,name=referral_id,json=referralId,proto3" json:"referral_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveTherapistResponse) Reset() {
	*x = ApproveTherapistResponse{}
	mi := &file_proto_therapist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveTherapistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveTherapistResponse) ProtoMessage() {}

func (x *ApproveTherapistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveTherapistResponse.ProtoReflect.Descriptor instead.
func (*ApproveTherapistResponse) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{7}
}

func (x *ApproveTherapistResponse) GetReferralId() string {
	if x != nil {
		return x.ReferralId
	}
	return ""
}

type RejectTherapistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TherapistId   string                 `protobuf:"bytes,1,opt,name=therapist_id,json=therapistId,proto3" json:"therapist_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectTherapistRequest) Reset() {
	*x = RejectTherapistRequest{}
	mi := &file_proto_therapist_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectTherapistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectTherapistRequest) ProtoMessage() {}

func (x *RejectTherapistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectTherapistRequest.ProtoReflect.Descriptor instead.
func (*RejectTherapistRequest) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{8}
}

func (x *RejectTherapistRequest) GetTherapistId() string {
	if x != nil {
		return x.TherapistId
	}
	return ""
}

func (x *RejectTherapistRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RejectTherapistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectTherapistResponse) Reset() {
	*x = RejectTherapistResponse{}
	mi := &file_proto_therapist_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectTherapistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectTherapistResponse) ProtoMessage() {}

func (x *RejectTherapistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectTherapistResponse.ProtoReflect.Descriptor instead.
func (*RejectTherapistResponse) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{9}
}

func (x *RejectTherapistResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UploadFileRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Data     []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // raw file bytes (max 3 MB)
	FileName string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// "profile_photo" | "degree_certificate" | "government_id"
	FileType      string `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_proto_therapist_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{10}
}

func (x *UploadFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadFileRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // storage URL (stub for now)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_proto_therapist_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{11}
}

func (x *UploadFileResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_proto_therapist_proto protoreflect.FileDescriptor

const file_proto_therapist_proto_rawDesc = "" +
	"\n" +
	"\x15proto/therapist.proto\x12\ttherapist\"<\n" +
	"\x13AuthCallbackRequest\x12%\n" +
	"\x0esupabase_token\x18\x01 \x01(\tR\rsupabaseToken\"\xd0\x01\n" +
	"\x14AuthCallbackResponse\x12!\n" +
	"\ftherapist_id\x18\x01 \x01(\tR\vtherapistId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x121\n" +
	"\x14onboarding_completed\x18\x03 \x01(\bR\x13onboardingCompleted\x12\x1f\n" +
	"\vreferral_id\x18\x04 \x01(\tR\n" +
	"referralId\x12)\n" +
	"\x10rejection_reason\x18\x05 \x01(\tR\x0frejectionReason\"9\n" +
	"\x10GetStatusRequest\x12%\n" +
	"\x0esupabase_token\x18\x01 \x01(\tR\rsupabaseToken\"\xcd\x01\n" +
	"\x11GetStatusResponse\x12!\n" +
	"\ftherapist_id\x18\x01 \x01(\tR\vtherapistId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x121\n" +
	"\x14onboarding_completed\x18\x03 \x01(\bR\x13onboardingCompleted\x12\x1f\n" +
	"\vreferral_id\x18\x04 \x01(\tR\n" +
	"referralId\x12)\n" +
	"\x10rejection_reason\x18\x05 \x01(\tR\x0frejectionReason\"\xc0\x04\n" +
	"\x19CompleteOnboardingRequest\x12!\n" +
	"\ftherapist_id\x18\x01 \x01(\tR\vtherapistId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12)\n" +
	"\x10languages_spoken\x18\x03 \x03(\tR\x0flanguagesSpoken\x12(\n" +
	"\x0fspecializations\x18\x04 \x03(\tR\x0fspecializations\x12.\n" +
	"\x13years_of_experience\x18\x05 \x01(\x05R\x11yearsOfExperience\x12\x1f\n" +
	"\vsession_fee\x18\x06 \x01(\tR\n" +
	"sessionFee\x12#\n" +
	"\rsession_types\x18\a \x03(\tR\fsessionTypes\x12-\n" +
	"\x12degree_certificate\x18\b \x01(\tR\x11degreeCertificate\x12/\n" +
	"\x13registration_number\x18\t \x01(\tR\x12registrationNumber\x12!\n" +
	"\fissuing_body\x18\n" +
	" \x01(\tR\vissuingBody\x12\x16\n" +
	"\x06gender\x18\v \x01(\tR\x06gender\x12\x10\n" +
	"\x03bio\x18\f \x01(\tR\x03bio\x12#\n" +
	"\rprofile_photo\x18\r \x01(\tR\fprofilePhoto\x12!\n" +
	"\fphone_number\x18\x0e \x01(\tR\vphoneNumber\x12#\n" +
	"\rgovernment_id\x18\x0f \x01(\tR\fgovernmentId\"6\n" +
	"\x1aCompleteOnboardingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"<\n" +
	"\x17ApproveTherapistRequest\x12!\n" +
	"\ftherapist_id\x18\x01 \x01(\tR\vtherapistId\";\n" +
	"\x18ApproveTherapistResponse\x12\x1f\n" +
	"\vreferral_id\x18\x01 \x01(\tR\n" +
	"referralId\"S\n" +
	"\x16RejectTherapistRequest\x12!\n" +
	"\ftherapist_id\x18\x01 \x01(\tR\vtherapistId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"3\n" +
	"\x17RejectTherapistResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"a\n" +
	"\x11UploadFileRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\x03 \x01(\tR\bfileType\"&\n" +
	"\x12UploadFileResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2\x90\x04\n" +
	"\x10TherapistService\x12O\n" +
	"\fAuthCallback\x12\x1e.therapist.AuthCallbackRequest\x1a\x1f.therapist.AuthCallbackResponse\x12F\n" +
	"\tGetStatus\x12\x1b.therapist.GetStatusRequest\x1a\x1c.therapist.GetStatusResponse\x12a\n" +
	"\x12CompleteOnboarding\x12$.therapist.CompleteOnboardingRequest\x1a%.therapist.CompleteOnboardingResponse\x12[\n" +
	"\x10ApproveTherapist\x12\".therapist.ApproveTherapistRequest\x1a#.therapist.ApproveTherapistResponse\x12X\n" +
	"\x0fRejectTherapist\x12!.therapist.RejectTherapistRequest\x1a\".therapist.RejectTherapistResponse\x12I\n" +
	"\n" +
	"UploadFile\x12\x1c.therapist.UploadFileRequest\x1a\x1d.therapist.UploadFileResponseB-Z+therapist/pkg/proto/therapistpb;therapistpbb\x06proto3"

var (
	file_proto_therapist_proto_rawDescOnce sync.Once
	file_proto_therapist_proto_rawDescData []byte
)

func file_proto_therapist_proto_rawDescGZIP() []byte {
	file_proto_therapist_proto_rawDescOnce.Do(func() {
		file_proto_therapist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_therapist_proto_rawDesc), len(file_proto_therapist_proto_rawDesc)))
	})
	return file_proto_therapist_proto_rawDescData
}

var file_proto_therapist_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_therapist_proto_goTypes = []any{
	(*AuthCallbackRequest)(nil),        // 0: therapist.AuthCallbackRequest
	(*AuthCallbackResponse)(nil),       // 1: therapist.AuthCallbackResponse
	(*GetStatusRequest)(nil),           // 2: therapist.GetStatusRequest
	(*GetStatusResponse)(nil),          // 3: therapist.GetStatusResponse
	(*CompleteOnboardingRequest)(nil),  // 4: therapist.CompleteOnboardingRequest
	(*CompleteOnboardingResponse)(nil), // 5: therapist.CompleteOnboardingResponse
	(*ApproveTherapistRequest)(nil),    // 6: therapist.ApproveTherapistRequest
	(*ApproveTherapistResponse)(nil),   // 7: therapist.ApproveTherapistResponse
	(*RejectTherapistRequest)(nil),     // 8: therapist.RejectTherapistRequest
	(*RejectTherapistResponse)(nil),    // 9: therapist.RejectTherapistResponse
	(*UploadFileRequest)(nil),          // 10: therapist.UploadFileRequest
	(*UploadFileResponse)(nil),         // 11: therapist.UploadFileResponse
}
var file_proto_therapist_proto_depIdxs = []int32{
	0,  // 0: therapist.TherapistService.AuthCallback:input_type -> therapist.AuthCallbackRequest
	2,  // 1: therapist.TherapistService.GetStatus:input_type -> therapist.GetStatusRequest
	4,  // 2: therapist.TherapistService.CompleteOnboarding:input_type -> therapist.CompleteOnboardingRequest
	6,  // 3: therapist.TherapistService.ApproveTherapist:input_type -> therapist.ApproveTherapistRequest
	8,  // 4: therapist.TherapistService.RejectTherapist:input_type -> therapist.RejectTherapistRequest
	10, // 5: therapist.TherapistService.UploadFile:input_type -> therapist.UploadFileRequest
	1,  // 6: therapist.TherapistService.AuthCallback:output_type -> therapist.AuthCallbackResponse
	3,  // 7: therapist.TherapistService.GetStatus:output_type -> therapist.GetStatusResponse
	5,  // 8: therapist.TherapistService.CompleteOnboarding:output_type -> therapist.CompleteOnboardingResponse
	7,  // 9: therapist.TherapistService.ApproveTherapist:output_type -> therapist.ApproveTherapistResponse
	9,  // 10: therapist.TherapistService.RejectTherapist:output_type -> therapist.RejectTherapistResponse
	11, // 11: therapist.TherapistService.UploadFile:output_type -> therapist.UploadFileResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_therapist_proto_init() }
func file_proto_therapist_proto_init() {
	if File_proto_therapist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_therapist_proto_rawDesc), len(file_proto_therapist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_therapist_proto_goTypes,
		DependencyIndexes: file_proto_therapist_proto_depIdxs,
		MessageInfos:      file_proto_therapist_proto_msgTypes,
	}.Build()
	File_proto_therapist_proto = out.File
	file_proto_therapist_proto_goTypes = nil
	file_proto_therapist_proto_depIdxs = nil
}
