// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.24.3
// source: proto/therapist.proto

package therapistpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TherapistService_AuthCallback_FullMethodName       = "/therapist.TherapistService/AuthCallback"
	TherapistService_GetStatus_FullMethodName          = "/therapist.TherapistService/GetStatus"
	TherapistService_CompleteOnboarding_FullMethodName = "/therapist.TherapistService/CompleteOnboarding"
	TherapistService_ApproveTherapist_FullMethodName   = "/therapist.TherapistService/ApproveTherapist"
	TherapistService_RejectTherapist_FullMethodName    = "/therapist.TherapistService/RejectTherapist"
	TherapistService_UploadFile_FullMethodName         = "/therapist.TherapistService/UploadFile"
)

// TherapistServiceClient is the client API for TherapistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TherapistServiceClient interface {
	// Called after Supabase auth. Upserts the therapist and returns their state.
	AuthCallback(ctx context.Context, in *AuthCallbackRequest, opts ...grpc.CallOption) (*AuthCallbackResponse, error)
	// Returns the current state for an already-authenticated therapist.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// Saves the full onboarding form (sets status = pending).
	CompleteOnboarding(ctx context.Context, in *CompleteOnboardingRequest, opts ...grpc.CallOption) (*CompleteOnboardingResponse, error)
	// Admin: approve a therapist (generates referral ID, sets status = verified).
	ApproveTherapist(ctx context.Context, in *ApproveTherapistRequest, opts ...grpc.CallOption) (*ApproveTherapistResponse, error)
	// Admin: reject a therapist with an optional reason.
	RejectTherapist(ctx context.Context, in *RejectTherapistRequest, opts ...grpc.CallOption) (*RejectTherapistResponse, error)
	// Upload a file (profile photo, degree certificate, government ID).
	// Returns a URL string. Max 3 MB enforced server-side.
	UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
}

type therapistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTherapistServiceClient(cc grpc.ClientConnInterface) TherapistServiceClient {
	return &therapistServiceClient{cc}
}

func (c *therapistServiceClient) AuthCallback(ctx context.Context, in *AuthCallbackRequest, opts ...grpc.CallOption) (*AuthCallbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthCallbackResponse)
	err := c.cc.Invoke(ctx, TherapistService_AuthCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, TherapistService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) CompleteOnboarding(ctx context.Context, in *CompleteOnboardingRequest, opts ...grpc.CallOption) (*CompleteOnboardingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteOnboardingResponse)
	err := c.cc.Invoke(ctx, TherapistService_CompleteOnboarding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) ApproveTherapist(ctx context.Context, in *ApproveTherapistRequest, opts ...grpc.CallOption) (*ApproveTherapistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveTherapistResponse)
	err := c.cc.Invoke(ctx, TherapistService_ApproveTherapist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) RejectTherapist(ctx context.Context, in *RejectTherapistRequest, opts ...grpc.CallOption) (*RejectTherapistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectTherapistResponse)
	err := c.cc.Invoke(ctx, TherapistService_RejectTherapist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadFileResponse)
	err := c.cc.Invoke(ctx, TherapistService_UploadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TherapistServiceServer is the server API for TherapistService service.
// All implementations must embed UnimplementedTherapistServiceServer
// for forward compatibility.
type TherapistServiceServer interface {
	// Called after Supabase auth. Upserts the therapist and returns their state.
	AuthCallback(context.Context, *AuthCallbackRequest) (*AuthCallbackResponse, error)
	// Returns the current state for an already-authenticated therapist.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// Saves the full onboarding form (sets status = pending).
	CompleteOnboarding(context.Context, *CompleteOnboardingRequest) (*CompleteOnboardingResponse, error)
	// Admin: approve a therapist (generates referral ID, sets status = verified).
	ApproveTherapist(context.Context, *ApproveTherapistRequest) (*ApproveTherapistResponse, error)
	// Admin: reject a therapist with an optional reason.
	RejectTherapist(context.Context, *RejectTherapistRequest) (*RejectTherapistResponse, error)
	// Upload a file (profile photo, degree certificate, government ID).
	// Returns a URL string. Max 3 MB enforced server-side.
	UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error)
	mustEmbedUnimplementedTherapistServiceServer()
}

// UnimplementedTherapistServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTherapistServiceServer struct{}

func (UnimplementedTherapistServiceServer) AuthCallback(context.Context, *AuthCallbackRequest) (*AuthCallbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthCallback not implemented")
}
func (UnimplementedTherapistServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedTherapistServiceServer) CompleteOnboarding(context.Context, *CompleteOnboardingRequest) (*CompleteOnboardingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteOnboarding not implemented")
}
func (UnimplementedTherapistServiceServer) ApproveTherapist(context.Context, *ApproveTherapistRequest) (*ApproveTherapistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveTherapist not implemented")
}
func (UnimplementedTherapistServiceServer) RejectTherapist(context.Context, *RejectTherapistRequest) (*RejectTherapistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectTherapist not implemented")
}
func (UnimplementedTherapistServiceServer) UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedTherapistServiceServer) mustEmbedUnimplementedTherapistServiceServer() {}
func (UnimplementedTherapistServiceServer) testEmbeddedByValue()                          {}

// UnsafeTherapistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TherapistServiceServer will
// result in compilation errors.
type UnsafeTherapistServiceServer interface {
	mustEmbedUnimplementedTherapistServiceServer()
}

func RegisterTherapistServiceServer(s grpc.ServiceRegistrar, srv TherapistServiceServer) {
	// If the following call panics, it indicates UnimplementedTherapistServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TherapistService_ServiceDesc, srv)
}

func _TherapistService_AuthCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).AuthCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_AuthCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).AuthCallback(ctx, req.(*AuthCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_CompleteOnboarding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteOnboardingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).CompleteOnboarding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_CompleteOnboarding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).CompleteOnboarding(ctx, req.(*CompleteOnboardingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_ApproveTherapist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveTherapistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).ApproveTherapist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_ApproveTherapist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).ApproveTherapist(ctx, req.(*ApproveTherapistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_RejectTherapist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectTherapistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).RejectTherapist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_RejectTherapist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).RejectTherapist(ctx, req.(*RejectTherapistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_UploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).UploadFile(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TherapistService_ServiceDesc is the grpc.ServiceDesc for TherapistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TherapistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "therapist.TherapistService",
	HandlerType: (*TherapistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthCallback",
			Handler:    _TherapistService_AuthCallback_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _TherapistService_GetStatus_Handler,
		},
		{
			MethodName: "CompleteOnboarding",
			Handler:    _TherapistService_CompleteOnboarding_Handler,
		},
		{
			MethodName: "ApproveTherapist",
			Handler:    _TherapistService_ApproveTherapist_Handler,
		},
		{
			MethodName: "RejectTherapist",
			Handler:    _TherapistService_RejectTherapist_Handler,
		},
		{
			MethodName: "UploadFile",
			Handler:    _TherapistService_UploadFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/therapist.proto",
}
