// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/therapist.proto

package therapistpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SupabaseToken string                 `protobuf:"bytes,1,opt,name=supabase_token,json=supabaseToken,proto3" json:"supabase_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthCallbackRequest) Reset() {
	*x = AuthCallbackRequest{}
	mi := &file_proto_therapist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthCallbackRequest) ProtoMessage() {}

func (x *AuthCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthCallbackRequest.ProtoReflect.Descriptor instead.
func (*AuthCallbackRequest) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{0}
}

func (x *AuthCallbackRequest) GetSupabaseToken() string {
	if x != nil {
		return x.SupabaseToken
	}
	return ""
}

type AuthCallbackResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TherapistId string                 `protobuf:"bytes,1,opt,name=therapist_id,json=therapistId,proto3" json:"therapist_id,omitempty"`
	// "needs_onboarding" | "pending" | "verified" | "rejected"
	Status              string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	OnboardingCompleted bool   `protobuf:"varint,3,opt,name=onboarding_completed,json=onboardingCompleted,proto3" json:"onboarding_completed,omitempty"`
	ReferralId          string `protobuf:"bytes,4,opt,name=referral_id,json=referralId,proto3" json:"referral_id,omitempty"`
	RejectionReason     string `protobuf:"bytes,5,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	// Session tokens
	AccessToken   string `protobuf:"bytes,6,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string `protobuf:"bytes,7,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     int64  `protobuf:"varint,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp — access token expiry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthCallbackResponse) Reset() {
	*x = AuthCallbackResponse{}
	mi := &file_proto_therapist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthCallbackResponse) ProtoMessage() {}

func (x *AuthCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthCallbackResponse.ProtoReflect.Descriptor instead.
func (*AuthCallbackResponse) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{1}
}

func (x *AuthCallbackResponse) GetTherapistId() string {
	if x != nil {
		return x.TherapistId
	}
	return ""
}

func (x *AuthCallbackResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AuthCallbackResponse) GetOnboardingCompleted() bool {
	if x != nil {
		return x.OnboardingCompleted
	}
	return false
}

func (x *AuthCallbackResponse) GetReferralId() string {
	if x != nil {
		return x.ReferralId
	}
	return ""
}

func (x *AuthCallbackResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *AuthCallbackResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthCallbackResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *AuthCallbackResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SupabaseToken string                 `protobuf:"bytes,1,opt,name=supabase_token,json=supabaseToken,proto3" json:"supabase_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_proto_therapist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatusRequest) GetSupabaseToken() string {
	if x != nil {
		return x.SupabaseToken
	}
	return ""
}

type GetStatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TherapistId         string                 `protobuf:"bytes,1,opt,name=therapist_id,json=therapistId,proto3" json:"therapist_id,omitempty"`
	Status              string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	OnboardingCompleted bool                   `protobuf:"varint,3,opt,name=onboarding_completed,json=onboardingCompleted,proto3" json:"onboarding_completed,omitempty"`
	ReferralId          string                 `protobuf:"bytes,4,opt,name=referral_id,json=referralId,proto3" json:"referral_id,omitempty"`
	RejectionReason     string                 `protobuf:"bytes,5,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_proto_therapist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetTherapistId() string {
	if x != nil {
		return x.TherapistId
	}
	return ""
}

func (x *GetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetStatusResponse) GetOnboardingCompleted() bool {
	if x != nil {
		return x.OnboardingCompleted
	}
	return false
}

func (x *GetStatusResponse) GetReferralId() string {
	if x != nil {
		return x.ReferralId
	}
	return ""
}

func (x *GetStatusResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

type CompleteOnboardingRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TherapistId string                 `protobuf:"bytes,1,opt,name=therapist_id,json=therapistId,proto3" json:"therapist_id,omitempty"`
	// Required
	FullName           string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	LanguagesSpoken    []string `protobuf:"bytes,3,rep,name=languages_spoken,json=languagesSpoken,proto3" json:"languages_spoken,omitempty"`
	Specializations    []string `protobuf:"bytes,4,rep,name=specializations,proto3" json:"specializations,omitempty"`
	YearsOfExperience  int32    `protobuf:"varint,5,opt,name=years_of_experience,json=yearsOfExperience,proto3" json:"years_of_experience,omitempty"`
	SessionFee         string   `protobuf:"bytes,6,opt,name=session_fee,json=sessionFee,proto3" json:"session_fee,omitempty"`       // decimal string e.g. "1500.00"
	SessionTypes       []string `protobuf:"bytes,7,rep,name=session_types,json=sessionTypes,proto3" json:"session_types,omitempty"` // "video" | "in_person"
	DegreeCertificate  string   `protobuf:"bytes,8,opt,name=degree_certificate,json=degreeCertificate,proto3" json:"degree_certificate,omitempty"`
	RegistrationNumber string   `protobuf:"bytes,9,opt,name=registration_number,json=registrationNumber,proto3" json:"registration_number,omitempty"`
	IssuingBody        string   `protobuf:"bytes,10,opt,name=issuing_body,json=issuingBody,proto3" json:"issuing_body,omitempty"`
	// Optional
	Gender       string `protobuf:"bytes,11,opt,name=gender,proto3" json:"gender,omitempty"`
	Bio          string `protobuf:"bytes,12,opt,name=bio,proto3" json:"bio,omitempty"`
	ProfilePhoto string `protobuf:"bytes,13,opt,name=profile_photo,json=profilePhoto,proto3" json:"profile_photo,omitempty"`
	PhoneNumber  string `protobuf:"bytes,14,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	GovernmentId string `protobuf:"bytes,15,opt,name=government_id,json=governmentId,proto3" json:"government_id,omitempty"`
	// Required when session_types contains "in_person"
	AddressText   string  `protobuf:"bytes,16,opt,name=address_text,json=addressText,proto3" json:"address_text,omitempty"`
	Latitude      float64 `protobuf:"fixed64,17,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64 `protobuf:"fixed64,18,opt,name=longitude,proto3" json:"longitude,omitempty"`
	PlaceId       string  `protobuf:"bytes,19,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	AddressState  string  `protobuf:"bytes,20,opt,name=address_state,json=addressState,proto3" json:"address_state,omitempty"`    // e.g. "Maharashtra"
	AddressNation string  `protobuf:"bytes,21,opt,name=address_nation,json=addressNation,proto3" json:"address_nation,omitempty"` // e.g. "India"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOnboardingRequest) Reset() {
	*x = CompleteOnboardingRequest{}
	mi := &file_proto_therapist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOnboardingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOnboardingRequest) ProtoMessage() {}

func (x *CompleteOnboardingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOnboardingRequest.ProtoReflect.Descriptor instead.
func (*CompleteOnboardingRequest) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteOnboardingRequest) GetTherapistId() string {
	if x != nil {
		return x.TherapistId
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetLanguagesSpoken() []string {
	if x != nil {
		return x.LanguagesSpoken
	}
	return nil
}

func (x *CompleteOnboardingRequest) GetSpecializations() []string {
	if x != nil {
		return x.Specializations
	}
	return nil
}

func (x *CompleteOnboardingRequest) GetYearsOfExperience() int32 {
	if x != nil {
		return x.YearsOfExperience
	}
	return 0
}

func (x *CompleteOnboardingRequest) GetSessionFee() string {
	if x != nil {
		return x.SessionFee
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetSessionTypes() []string {
	if x != nil {
		return x.SessionTypes
	}
	return nil
}

func (x *CompleteOnboardingRequest) GetDegreeCertificate() string {
	if x != nil {
		return x.DegreeCertificate
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetRegistrationNumber() string {
	if x != nil {
		return x.RegistrationNumber
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetIssuingBody() string {
	if x != nil {
		return x.IssuingBody
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetProfilePhoto() string {
	if x != nil {
		return x.ProfilePhoto
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetGovernmentId() string {
	if x != nil {
		return x.GovernmentId
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetAddressText() string {
	if x != nil {
		return x.AddressText
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CompleteOnboardingRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CompleteOnboardingRequest) GetPlaceId() string {
	if x != nil {
		return x.PlaceId
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetAddressState() string {
	if x != nil {
		return x.AddressState
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetAddressNation() string {
	if x != nil {
		return x.AddressNation
	}
	return ""
}

type CompleteOnboardingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOnboardingResponse) Reset() {
	*x = CompleteOnboardingResponse{}
	mi := &file_proto_therapist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOnboardingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOnboardingResponse) ProtoMessage() {}

func (x *CompleteOnboardingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOnboardingResponse.ProtoReflect.Descriptor instead.
func (*CompleteOnboardingResponse) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteOnboardingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ApproveTherapistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TherapistId   string                 `protobuf:"bytes,1,opt,name=therapist_id,json=therapistId,proto3" json:"therapist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveTherapistRequest) Reset() {
	*x = ApproveTherapistRequest{}
	mi := &file_proto_therapist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveTherapistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveTherapistRequest) ProtoMessage() {}

func (x *ApproveTherapistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveTherapistRequest.ProtoReflect.Descriptor instead.
func (*ApproveTherapistRequest) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{6}
}

func (x *ApproveTherapistRequest) GetTherapistId() string {
	if x != nil {
		return x.TherapistId
	}
	return ""
}

type ApproveTherapistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReferralId    string                 `protobuf:"bytes,1,opt,name=referral_id,json=referralId,proto3" json:"referral_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveTherapistResponse) Reset() {
	*x = ApproveTherapistResponse{}
	mi := &file_proto_therapist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveTherapistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveTherapistResponse) ProtoMessage() {}

func (x *ApproveTherapistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveTherapistResponse.ProtoReflect.Descriptor instead.
func (*ApproveTherapistResponse) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{7}
}

func (x *ApproveTherapistResponse) GetReferralId() string {
	if x != nil {
		return x.ReferralId
	}
	return ""
}

type RejectTherapistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TherapistId   string                 `protobuf:"bytes,1,opt,name=therapist_id,json=therapistId,proto3" json:"therapist_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectTherapistRequest) Reset() {
	*x = RejectTherapistRequest{}
	mi := &file_proto_therapist_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectTherapistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectTherapistRequest) ProtoMessage() {}

func (x *RejectTherapistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectTherapistRequest.ProtoReflect.Descriptor instead.
func (*RejectTherapistRequest) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{8}
}

func (x *RejectTherapistRequest) GetTherapistId() string {
	if x != nil {
		return x.TherapistId
	}
	return ""
}

func (x *RejectTherapistRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RejectTherapistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectTherapistResponse) Reset() {
	*x = RejectTherapistResponse{}
	mi := &file_proto_therapist_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectTherapistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectTherapistResponse) ProtoMessage() {}

func (x *RejectTherapistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectTherapistResponse.ProtoReflect.Descriptor instead.
func (*RejectTherapistResponse) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{9}
}

func (x *RejectTherapistResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UploadFileRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Data     []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // raw file bytes (max 3 MB)
	FileName string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// "profile_photo" | "degree_certificate" | "government_id"
	FileType      string `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_proto_therapist_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{10}
}

func (x *UploadFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadFileRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // storage URL (stub for now)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_proto_therapist_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{11}
}

func (x *UploadFileResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type RefreshSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshSessionRequest) Reset() {
	*x = RefreshSessionRequest{}
	mi := &file_proto_therapist_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSessionRequest) ProtoMessage() {}

func (x *RefreshSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSessionRequest.ProtoReflect.Descriptor instead.
func (*RefreshSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{12}
}

func (x *RefreshSessionRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TherapistId   string                 `protobuf:"bytes,1,opt,name=therapist_id,json=therapistId,proto3" json:"therapist_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshSessionResponse) Reset() {
	*x = RefreshSessionResponse{}
	mi := &file_proto_therapist_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshSessionResponse) ProtoMessage() {}

func (x *RefreshSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshSessionResponse.ProtoReflect.Descriptor instead.
func (*RefreshSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{13}
}

func (x *RefreshSessionResponse) GetTherapistId() string {
	if x != nil {
		return x.TherapistId
	}
	return ""
}

func (x *RefreshSessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RefreshSessionResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshSessionResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshSessionResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_proto_therapist_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{14}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_proto_therapist_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_therapist_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_proto_therapist_proto_rawDescGZIP(), []int{15}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_therapist_proto protoreflect.FileDescriptor

const file_proto_therapist_proto_rawDesc = "" +
	"\n" +
	"\x15proto/therapist.proto\x12\ttherapist\x1a\x10proto/user.proto\x1a\x10proto/blog.proto\x1a\x15proto/discovery.proto\"<\n" +
	"\x13AuthCallbackRequest\x12%\n" +
	"\x0esupabase_token\x18\x01 \x01(\tR\rsupabaseToken\"\xb7\x02\n" +
	"\x14AuthCallbackResponse\x12!\n" +
	"\ftherapist_id\x18\x01 \x01(\tR\vtherapistId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x121\n" +
	"\x14onboarding_completed\x18\x03 \x01(\bR\x13onboardingCompleted\x12\x1f\n" +
	"\vreferral_id\x18\x04 \x01(\tR\n" +
	"referralId\x12)\n" +
	"\x10rejection_reason\x18\x05 \x01(\tR\x0frejectionReason\x12!\n" +
	"\faccess_token\x18\x06 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\a \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\x03R\texpiresAt\"9\n" +
	"\x10GetStatusRequest\x12%\n" +
	"\x0esupabase_token\x18\x01 \x01(\tR\rsupabaseToken\"\xcd\x01\n" +
	"\x11GetStatusResponse\x12!\n" +
	"\ftherapist_id\x18\x01 \x01(\tR\vtherapistId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x121\n" +
	"\x14onboarding_completed\x18\x03 \x01(\bR\x13onboardingCompleted\x12\x1f\n" +
	"\vreferral_id\x18\x04 \x01(\tR\n" +
	"referralId\x12)\n" +
	"\x10rejection_reason\x18\x05 \x01(\tR\x0frejectionReason\"\x84\x06\n" +
	"\x19CompleteOnboardingRequest\x12!\n" +
	"\ftherapist_id\x18\x01 \x01(\tR\vtherapistId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12)\n" +
	"\x10languages_spoken\x18\x03 \x03(\tR\x0flanguagesSpoken\x12(\n" +
	"\x0fspecializations\x18\x04 \x03(\tR\x0fspecializations\x12.\n" +
	"\x13years_of_experience\x18\x05 \x01(\x05R\x11yearsOfExperience\x12\x1f\n" +
	"\vsession_fee\x18\x06 \x01(\tR\n" +
	"sessionFee\x12#\n" +
	"\rsession_types\x18\a \x03(\tR\fsessionTypes\x12-\n" +
	"\x12degree_certificate\x18\b \x01(\tR\x11degreeCertificate\x12/\n" +
	"\x13registration_number\x18\t \x01(\tR\x12registrationNumber\x12!\n" +
	"\fissuing_body\x18\n" +
	" \x01(\tR\vissuingBody\x12\x16\n" +
	"\x06gender\x18\v \x01(\tR\x06gender\x12\x10\n" +
	"\x03bio\x18\f \x01(\tR\x03bio\x12#\n" +
	"\rprofile_photo\x18\r \x01(\tR\fprofilePhoto\x12!\n" +
	"\fphone_number\x18\x0e \x01(\tR\vphoneNumber\x12#\n" +
	"\rgovernment_id\x18\x0f \x01(\tR\fgovernmentId\x12!\n" +
	"\faddress_text\x18\x10 \x01(\tR\vaddressText\x12\x1a\n" +
	"\blatitude\x18\x11 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x12 \x01(\x01R\tlongitude\x12\x19\n" +
	"\bplace_id\x18\x13 \x01(\tR\aplaceId\x12#\n" +
	"\raddress_state\x18\x14 \x01(\tR\faddressState\x12%\n" +
	"\x0eaddress_nation\x18\x15 \x01(\tR\raddressNation\"6\n" +
	"\x1aCompleteOnboardingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"<\n" +
	"\x17ApproveTherapistRequest\x12!\n" +
	"\ftherapist_id\x18\x01 \x01(\tR\vtherapistId\";\n" +
	"\x18ApproveTherapistResponse\x12\x1f\n" +
	"\vreferral_id\x18\x01 \x01(\tR\n" +
	"referralId\"S\n" +
	"\x16RejectTherapistRequest\x12!\n" +
	"\ftherapist_id\x18\x01 \x01(\tR\vtherapistId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"3\n" +
	"\x17RejectTherapistResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"a\n" +
	"\x11UploadFileRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\x03 \x01(\tR\bfileType\"&\n" +
	"\x12UploadFileResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"<\n" +
	"\x15RefreshSessionRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\xba\x01\n" +
	"\x16RefreshSessionResponse\x12!\n" +
	"\ftherapist_id\x18\x01 \x01(\tR\vtherapistId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x81\x10\n" +
	"\x10TherapistService\x12O\n" +
	"\fAuthCallback\x12\x1e.therapist.AuthCallbackRequest\x1a\x1f.therapist.AuthCallbackResponse\x12F\n" +
	"\tGetStatus\x12\x1b.therapist.GetStatusRequest\x1a\x1c.therapist.GetStatusResponse\x12a\n" +
	"\x12CompleteOnboarding\x12$.therapist.CompleteOnboardingRequest\x1a%.therapist.CompleteOnboardingResponse\x12[\n" +
	"\x10ApproveTherapist\x12\".therapist.ApproveTherapistRequest\x1a#.therapist.ApproveTherapistResponse\x12X\n" +
	"\x0fRejectTherapist\x12!.therapist.RejectTherapistRequest\x1a\".therapist.RejectTherapistResponse\x12I\n" +
	"\n" +
	"UploadFile\x12\x1c.therapist.UploadFileRequest\x1a\x1d.therapist.UploadFileResponse\x12U\n" +
	"\x0eRefreshSession\x12 .therapist.RefreshSessionRequest\x1a!.therapist.RefreshSessionResponse\x12=\n" +
	"\x06Logout\x12\x18.therapist.LogoutRequest\x1a\x19.therapist.LogoutResponse\x12[\n" +
	"\x10UserAuthCallback\x12\".therapist.UserAuthCallbackRequest\x1a#.therapist.UserAuthCallbackResponse\x12m\n" +
	"\x16CompleteUserOnboarding\x12(.therapist.CompleteUserOnboardingRequest\x1a).therapist.CompleteUserOnboardingResponse\x12U\n" +
	"\x0eGetUserProfile\x12 .therapist.GetUserProfileRequest\x1a!.therapist.GetUserProfileResponse\x12a\n" +
	"\x12UserRefreshSession\x12$.therapist.UserRefreshSessionRequest\x1a%.therapist.UserRefreshSessionResponse\x12I\n" +
	"\n" +
	"UserLogout\x12\x1c.therapist.UserLogoutRequest\x1a\x1d.therapist.UserLogoutResponse\x12[\n" +
	"\x10SearchTherapists\x12\".therapist.SearchTherapistsRequest\x1a#.therapist.SearchTherapistsResponse\x12s\n" +
	"\x18GetRecommendedTherapists\x12*.therapist.GetRecommendedTherapistsRequest\x1a+.therapist.GetRecommendedTherapistsResponse\x12I\n" +
	"\n" +
	"CreateBlog\x12\x1c.therapist.CreateBlogRequest\x1a\x1d.therapist.CreateBlogResponse\x12I\n" +
	"\n" +
	"UpdateBlog\x12\x1c.therapist.UpdateBlogRequest\x1a\x1d.therapist.UpdateBlogResponse\x12L\n" +
	"\vPublishBlog\x12\x1d.therapist.PublishBlogRequest\x1a\x1e.therapist.PublishBlogResponse\x12I\n" +
	"\n" +
	"DeleteBlog\x12\x1c.therapist.DeleteBlogRequest\x1a\x1d.therapist.DeleteBlogResponse\x12@\n" +
	"\aGetBlog\x12\x19.therapist.GetBlogRequest\x1a\x1a.therapist.GetBlogResponse\x12F\n" +
	"\tListBlogs\x12\x1b.therapist.ListBlogsRequest\x1a\x1c.therapist.ListBlogsResponse\x12L\n" +
	"\vListMyBlogs\x12\x1d.therapist.ListMyBlogsRequest\x1a\x1e.therapist.ListMyBlogsResponse\x12U\n" +
	"\x0eToggleLikeBlog\x12 .therapist.ToggleLikeBlogRequest\x1a!.therapist.ToggleLikeBlogResponse\x12X\n" +
	"\x0fUploadBlogImage\x12!.therapist.UploadBlogImageRequest\x1a\".therapist.UploadBlogImageResponseB-Z+therapist/pkg/proto/therapistpb;therapistpbb\x06proto3"

var (
	file_proto_therapist_proto_rawDescOnce sync.Once
	file_proto_therapist_proto_rawDescData []byte
)

func file_proto_therapist_proto_rawDescGZIP() []byte {
	file_proto_therapist_proto_rawDescOnce.Do(func() {
		file_proto_therapist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_therapist_proto_rawDesc), len(file_proto_therapist_proto_rawDesc)))
	})
	return file_proto_therapist_proto_rawDescData
}

var file_proto_therapist_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_therapist_proto_goTypes = []any{
	(*AuthCallbackRequest)(nil),              // 0: therapist.AuthCallbackRequest
	(*AuthCallbackResponse)(nil),             // 1: therapist.AuthCallbackResponse
	(*GetStatusRequest)(nil),                 // 2: therapist.GetStatusRequest
	(*GetStatusResponse)(nil),                // 3: therapist.GetStatusResponse
	(*CompleteOnboardingRequest)(nil),        // 4: therapist.CompleteOnboardingRequest
	(*CompleteOnboardingResponse)(nil),       // 5: therapist.CompleteOnboardingResponse
	(*ApproveTherapistRequest)(nil),          // 6: therapist.ApproveTherapistRequest
	(*ApproveTherapistResponse)(nil),         // 7: therapist.ApproveTherapistResponse
	(*RejectTherapistRequest)(nil),           // 8: therapist.RejectTherapistRequest
	(*RejectTherapistResponse)(nil),          // 9: therapist.RejectTherapistResponse
	(*UploadFileRequest)(nil),                // 10: therapist.UploadFileRequest
	(*UploadFileResponse)(nil),               // 11: therapist.UploadFileResponse
	(*RefreshSessionRequest)(nil),            // 12: therapist.RefreshSessionRequest
	(*RefreshSessionResponse)(nil),           // 13: therapist.RefreshSessionResponse
	(*LogoutRequest)(nil),                    // 14: therapist.LogoutRequest
	(*LogoutResponse)(nil),                   // 15: therapist.LogoutResponse
	(*UserAuthCallbackRequest)(nil),          // 16: therapist.UserAuthCallbackRequest
	(*CompleteUserOnboardingRequest)(nil),    // 17: therapist.CompleteUserOnboardingRequest
	(*GetUserProfileRequest)(nil),            // 18: therapist.GetUserProfileRequest
	(*UserRefreshSessionRequest)(nil),        // 19: therapist.UserRefreshSessionRequest
	(*UserLogoutRequest)(nil),                // 20: therapist.UserLogoutRequest
	(*SearchTherapistsRequest)(nil),          // 21: therapist.SearchTherapistsRequest
	(*GetRecommendedTherapistsRequest)(nil),  // 22: therapist.GetRecommendedTherapistsRequest
	(*CreateBlogRequest)(nil),                // 23: therapist.CreateBlogRequest
	(*UpdateBlogRequest)(nil),                // 24: therapist.UpdateBlogRequest
	(*PublishBlogRequest)(nil),               // 25: therapist.PublishBlogRequest
	(*DeleteBlogRequest)(nil),                // 26: therapist.DeleteBlogRequest
	(*GetBlogRequest)(nil),                   // 27: therapist.GetBlogRequest
	(*ListBlogsRequest)(nil),                 // 28: therapist.ListBlogsRequest
	(*ListMyBlogsRequest)(nil),               // 29: therapist.ListMyBlogsRequest
	(*ToggleLikeBlogRequest)(nil),            // 30: therapist.ToggleLikeBlogRequest
	(*UploadBlogImageRequest)(nil),           // 31: therapist.UploadBlogImageRequest
	(*UserAuthCallbackResponse)(nil),         // 32: therapist.UserAuthCallbackResponse
	(*CompleteUserOnboardingResponse)(nil),   // 33: therapist.CompleteUserOnboardingResponse
	(*GetUserProfileResponse)(nil),           // 34: therapist.GetUserProfileResponse
	(*UserRefreshSessionResponse)(nil),       // 35: therapist.UserRefreshSessionResponse
	(*UserLogoutResponse)(nil),               // 36: therapist.UserLogoutResponse
	(*SearchTherapistsResponse)(nil),         // 37: therapist.SearchTherapistsResponse
	(*GetRecommendedTherapistsResponse)(nil), // 38: therapist.GetRecommendedTherapistsResponse
	(*CreateBlogResponse)(nil),               // 39: therapist.CreateBlogResponse
	(*UpdateBlogResponse)(nil),               // 40: therapist.UpdateBlogResponse
	(*PublishBlogResponse)(nil),              // 41: therapist.PublishBlogResponse
	(*DeleteBlogResponse)(nil),               // 42: therapist.DeleteBlogResponse
	(*GetBlogResponse)(nil),                  // 43: therapist.GetBlogResponse
	(*ListBlogsResponse)(nil),                // 44: therapist.ListBlogsResponse
	(*ListMyBlogsResponse)(nil),              // 45: therapist.ListMyBlogsResponse
	(*ToggleLikeBlogResponse)(nil),           // 46: therapist.ToggleLikeBlogResponse
	(*UploadBlogImageResponse)(nil),          // 47: therapist.UploadBlogImageResponse
}
var file_proto_therapist_proto_depIdxs = []int32{
	0,  // 0: therapist.TherapistService.AuthCallback:input_type -> therapist.AuthCallbackRequest
	2,  // 1: therapist.TherapistService.GetStatus:input_type -> therapist.GetStatusRequest
	4,  // 2: therapist.TherapistService.CompleteOnboarding:input_type -> therapist.CompleteOnboardingRequest
	6,  // 3: therapist.TherapistService.ApproveTherapist:input_type -> therapist.ApproveTherapistRequest
	8,  // 4: therapist.TherapistService.RejectTherapist:input_type -> therapist.RejectTherapistRequest
	10, // 5: therapist.TherapistService.UploadFile:input_type -> therapist.UploadFileRequest
	12, // 6: therapist.TherapistService.RefreshSession:input_type -> therapist.RefreshSessionRequest
	14, // 7: therapist.TherapistService.Logout:input_type -> therapist.LogoutRequest
	16, // 8: therapist.TherapistService.UserAuthCallback:input_type -> therapist.UserAuthCallbackRequest
	17, // 9: therapist.TherapistService.CompleteUserOnboarding:input_type -> therapist.CompleteUserOnboardingRequest
	18, // 10: therapist.TherapistService.GetUserProfile:input_type -> therapist.GetUserProfileRequest
	19, // 11: therapist.TherapistService.UserRefreshSession:input_type -> therapist.UserRefreshSessionRequest
	20, // 12: therapist.TherapistService.UserLogout:input_type -> therapist.UserLogoutRequest
	21, // 13: therapist.TherapistService.SearchTherapists:input_type -> therapist.SearchTherapistsRequest
	22, // 14: therapist.TherapistService.GetRecommendedTherapists:input_type -> therapist.GetRecommendedTherapistsRequest
	23, // 15: therapist.TherapistService.CreateBlog:input_type -> therapist.CreateBlogRequest
	24, // 16: therapist.TherapistService.UpdateBlog:input_type -> therapist.UpdateBlogRequest
	25, // 17: therapist.TherapistService.PublishBlog:input_type -> therapist.PublishBlogRequest
	26, // 18: therapist.TherapistService.DeleteBlog:input_type -> therapist.DeleteBlogRequest
	27, // 19: therapist.TherapistService.GetBlog:input_type -> therapist.GetBlogRequest
	28, // 20: therapist.TherapistService.ListBlogs:input_type -> therapist.ListBlogsRequest
	29, // 21: therapist.TherapistService.ListMyBlogs:input_type -> therapist.ListMyBlogsRequest
	30, // 22: therapist.TherapistService.ToggleLikeBlog:input_type -> therapist.ToggleLikeBlogRequest
	31, // 23: therapist.TherapistService.UploadBlogImage:input_type -> therapist.UploadBlogImageRequest
	1,  // 24: therapist.TherapistService.AuthCallback:output_type -> therapist.AuthCallbackResponse
	3,  // 25: therapist.TherapistService.GetStatus:output_type -> therapist.GetStatusResponse
	5,  // 26: therapist.TherapistService.CompleteOnboarding:output_type -> therapist.CompleteOnboardingResponse
	7,  // 27: therapist.TherapistService.ApproveTherapist:output_type -> therapist.ApproveTherapistResponse
	9,  // 28: therapist.TherapistService.RejectTherapist:output_type -> therapist.RejectTherapistResponse
	11, // 29: therapist.TherapistService.UploadFile:output_type -> therapist.UploadFileResponse
	13, // 30: therapist.TherapistService.RefreshSession:output_type -> therapist.RefreshSessionResponse
	15, // 31: therapist.TherapistService.Logout:output_type -> therapist.LogoutResponse
	32, // 32: therapist.TherapistService.UserAuthCallback:output_type -> therapist.UserAuthCallbackResponse
	33, // 33: therapist.TherapistService.CompleteUserOnboarding:output_type -> therapist.CompleteUserOnboardingResponse
	34, // 34: therapist.TherapistService.GetUserProfile:output_type -> therapist.GetUserProfileResponse
	35, // 35: therapist.TherapistService.UserRefreshSession:output_type -> therapist.UserRefreshSessionResponse
	36, // 36: therapist.TherapistService.UserLogout:output_type -> therapist.UserLogoutResponse
	37, // 37: therapist.TherapistService.SearchTherapists:output_type -> therapist.SearchTherapistsResponse
	38, // 38: therapist.TherapistService.GetRecommendedTherapists:output_type -> therapist.GetRecommendedTherapistsResponse
	39, // 39: therapist.TherapistService.CreateBlog:output_type -> therapist.CreateBlogResponse
	40, // 40: therapist.TherapistService.UpdateBlog:output_type -> therapist.UpdateBlogResponse
	41, // 41: therapist.TherapistService.PublishBlog:output_type -> therapist.PublishBlogResponse
	42, // 42: therapist.TherapistService.DeleteBlog:output_type -> therapist.DeleteBlogResponse
	43, // 43: therapist.TherapistService.GetBlog:output_type -> therapist.GetBlogResponse
	44, // 44: therapist.TherapistService.ListBlogs:output_type -> therapist.ListBlogsResponse
	45, // 45: therapist.TherapistService.ListMyBlogs:output_type -> therapist.ListMyBlogsResponse
	46, // 46: therapist.TherapistService.ToggleLikeBlog:output_type -> therapist.ToggleLikeBlogResponse
	47, // 47: therapist.TherapistService.UploadBlogImage:output_type -> therapist.UploadBlogImageResponse
	24, // [24:48] is the sub-list for method output_type
	0,  // [0:24] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_therapist_proto_init() }
func file_proto_therapist_proto_init() {
	if File_proto_therapist_proto != nil {
		return
	}
	file_proto_user_proto_init()
	file_proto_blog_proto_init()
	file_proto_discovery_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_therapist_proto_rawDesc), len(file_proto_therapist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_therapist_proto_goTypes,
		DependencyIndexes: file_proto_therapist_proto_depIdxs,
		MessageInfos:      file_proto_therapist_proto_msgTypes,
	}.Build()
	File_proto_therapist_proto = out.File
	file_proto_therapist_proto_goTypes = nil
	file_proto_therapist_proto_depIdxs = nil
}
