// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.24.3
// source: proto/therapist.proto

package therapistpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TherapistService_AuthCallback_FullMethodName             = "/therapist.TherapistService/AuthCallback"
	TherapistService_GetStatus_FullMethodName                = "/therapist.TherapistService/GetStatus"
	TherapistService_CompleteOnboarding_FullMethodName       = "/therapist.TherapistService/CompleteOnboarding"
	TherapistService_ApproveTherapist_FullMethodName         = "/therapist.TherapistService/ApproveTherapist"
	TherapistService_RejectTherapist_FullMethodName          = "/therapist.TherapistService/RejectTherapist"
	TherapistService_UploadFile_FullMethodName               = "/therapist.TherapistService/UploadFile"
	TherapistService_RefreshSession_FullMethodName           = "/therapist.TherapistService/RefreshSession"
	TherapistService_Logout_FullMethodName                   = "/therapist.TherapistService/Logout"
	TherapistService_UserAuthCallback_FullMethodName         = "/therapist.TherapistService/UserAuthCallback"
	TherapistService_CompleteUserOnboarding_FullMethodName   = "/therapist.TherapistService/CompleteUserOnboarding"
	TherapistService_GetUserProfile_FullMethodName           = "/therapist.TherapistService/GetUserProfile"
	TherapistService_UserRefreshSession_FullMethodName       = "/therapist.TherapistService/UserRefreshSession"
	TherapistService_UserLogout_FullMethodName               = "/therapist.TherapistService/UserLogout"
	TherapistService_SearchTherapists_FullMethodName         = "/therapist.TherapistService/SearchTherapists"
	TherapistService_GetRecommendedTherapists_FullMethodName = "/therapist.TherapistService/GetRecommendedTherapists"
	TherapistService_CreateBlog_FullMethodName               = "/therapist.TherapistService/CreateBlog"
	TherapistService_UpdateBlog_FullMethodName               = "/therapist.TherapistService/UpdateBlog"
	TherapistService_PublishBlog_FullMethodName              = "/therapist.TherapistService/PublishBlog"
	TherapistService_DeleteBlog_FullMethodName               = "/therapist.TherapistService/DeleteBlog"
	TherapistService_GetBlog_FullMethodName                  = "/therapist.TherapistService/GetBlog"
	TherapistService_ListBlogs_FullMethodName                = "/therapist.TherapistService/ListBlogs"
	TherapistService_ListMyBlogs_FullMethodName              = "/therapist.TherapistService/ListMyBlogs"
	TherapistService_ToggleLikeBlog_FullMethodName           = "/therapist.TherapistService/ToggleLikeBlog"
	TherapistService_UploadBlogImage_FullMethodName          = "/therapist.TherapistService/UploadBlogImage"
)

// TherapistServiceClient is the client API for TherapistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TherapistServiceClient interface {
	// ── Therapist auth / onboarding ───────────────────────────────────────────
	// Called after Supabase auth. Upserts the therapist and returns their state + tokens.
	AuthCallback(ctx context.Context, in *AuthCallbackRequest, opts ...grpc.CallOption) (*AuthCallbackResponse, error)
	// Returns the current state for an already-authenticated therapist.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// Saves the full onboarding form (sets status = pending).
	CompleteOnboarding(ctx context.Context, in *CompleteOnboardingRequest, opts ...grpc.CallOption) (*CompleteOnboardingResponse, error)
	// Admin: approve a therapist (generates referral ID, sets status = verified).
	ApproveTherapist(ctx context.Context, in *ApproveTherapistRequest, opts ...grpc.CallOption) (*ApproveTherapistResponse, error)
	// Admin: reject a therapist with an optional reason.
	RejectTherapist(ctx context.Context, in *RejectTherapistRequest, opts ...grpc.CallOption) (*RejectTherapistResponse, error)
	// Upload a file (profile photo, degree certificate, government ID).
	// Returns a URL string. Max 3 MB enforced server-side.
	UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
	// Exchange a valid refresh token for a new access + refresh token pair.
	RefreshSession(ctx context.Context, in *RefreshSessionRequest, opts ...grpc.CallOption) (*RefreshSessionResponse, error)
	// Invalidate the refresh token (log out this device).
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	// ── User (client/patient) auth / onboarding ───────────────────────────────
	// Called after Supabase auth for users (clients looking for a therapist).
	UserAuthCallback(ctx context.Context, in *UserAuthCallbackRequest, opts ...grpc.CallOption) (*UserAuthCallbackResponse, error)
	// Saves the user onboarding form.
	CompleteUserOnboarding(ctx context.Context, in *CompleteUserOnboardingRequest, opts ...grpc.CallOption) (*CompleteUserOnboardingResponse, error)
	// Fetch the authenticated user's own profile.
	GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error)
	// Exchange a user refresh token for a new access + refresh token pair.
	UserRefreshSession(ctx context.Context, in *UserRefreshSessionRequest, opts ...grpc.CallOption) (*UserRefreshSessionResponse, error)
	// Invalidate the user refresh token (log out this device).
	UserLogout(ctx context.Context, in *UserLogoutRequest, opts ...grpc.CallOption) (*UserLogoutResponse, error)
	// ── Discovery (user-facing) ───────────────────────────────────────────────
	// Full-text search across verified therapists.
	SearchTherapists(ctx context.Context, in *SearchTherapistsRequest, opts ...grpc.CallOption) (*SearchTherapistsResponse, error)
	// Location + rating-based recommendations for a user.
	GetRecommendedTherapists(ctx context.Context, in *GetRecommendedTherapistsRequest, opts ...grpc.CallOption) (*GetRecommendedTherapistsResponse, error)
	// ── Blog ──────────────────────────────────────────────────────────────────
	// Create a draft blog (verified therapists only).
	CreateBlog(ctx context.Context, in *CreateBlogRequest, opts ...grpc.CallOption) (*CreateBlogResponse, error)
	// Update a draft blog (owner only).
	UpdateBlog(ctx context.Context, in *UpdateBlogRequest, opts ...grpc.CallOption) (*UpdateBlogResponse, error)
	// Publish a draft blog (owner only).
	PublishBlog(ctx context.Context, in *PublishBlogRequest, opts ...grpc.CallOption) (*PublishBlogResponse, error)
	// Delete a blog (owner only).
	DeleteBlog(ctx context.Context, in *DeleteBlogRequest, opts ...grpc.CallOption) (*DeleteBlogResponse, error)
	// Fetch a single blog; increments view count for published blogs.
	GetBlog(ctx context.Context, in *GetBlogRequest, opts ...grpc.CallOption) (*GetBlogResponse, error)
	// List published blogs (optionally filtered by therapist).
	ListBlogs(ctx context.Context, in *ListBlogsRequest, opts ...grpc.CallOption) (*ListBlogsResponse, error)
	// List all blogs (draft + published) for the authenticated therapist.
	ListMyBlogs(ctx context.Context, in *ListMyBlogsRequest, opts ...grpc.CallOption) (*ListMyBlogsResponse, error)
	// Toggle like on a published blog.
	ToggleLikeBlog(ctx context.Context, in *ToggleLikeBlogRequest, opts ...grpc.CallOption) (*ToggleLikeBlogResponse, error)
	// Upload a single inline blog image (max 2 MB).
	UploadBlogImage(ctx context.Context, in *UploadBlogImageRequest, opts ...grpc.CallOption) (*UploadBlogImageResponse, error)
}

type therapistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTherapistServiceClient(cc grpc.ClientConnInterface) TherapistServiceClient {
	return &therapistServiceClient{cc}
}

func (c *therapistServiceClient) AuthCallback(ctx context.Context, in *AuthCallbackRequest, opts ...grpc.CallOption) (*AuthCallbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthCallbackResponse)
	err := c.cc.Invoke(ctx, TherapistService_AuthCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, TherapistService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) CompleteOnboarding(ctx context.Context, in *CompleteOnboardingRequest, opts ...grpc.CallOption) (*CompleteOnboardingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteOnboardingResponse)
	err := c.cc.Invoke(ctx, TherapistService_CompleteOnboarding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) ApproveTherapist(ctx context.Context, in *ApproveTherapistRequest, opts ...grpc.CallOption) (*ApproveTherapistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveTherapistResponse)
	err := c.cc.Invoke(ctx, TherapistService_ApproveTherapist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) RejectTherapist(ctx context.Context, in *RejectTherapistRequest, opts ...grpc.CallOption) (*RejectTherapistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectTherapistResponse)
	err := c.cc.Invoke(ctx, TherapistService_RejectTherapist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadFileResponse)
	err := c.cc.Invoke(ctx, TherapistService_UploadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) RefreshSession(ctx context.Context, in *RefreshSessionRequest, opts ...grpc.CallOption) (*RefreshSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshSessionResponse)
	err := c.cc.Invoke(ctx, TherapistService_RefreshSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, TherapistService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) UserAuthCallback(ctx context.Context, in *UserAuthCallbackRequest, opts ...grpc.CallOption) (*UserAuthCallbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserAuthCallbackResponse)
	err := c.cc.Invoke(ctx, TherapistService_UserAuthCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) CompleteUserOnboarding(ctx context.Context, in *CompleteUserOnboardingRequest, opts ...grpc.CallOption) (*CompleteUserOnboardingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteUserOnboardingResponse)
	err := c.cc.Invoke(ctx, TherapistService_CompleteUserOnboarding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserProfileResponse)
	err := c.cc.Invoke(ctx, TherapistService_GetUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) UserRefreshSession(ctx context.Context, in *UserRefreshSessionRequest, opts ...grpc.CallOption) (*UserRefreshSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserRefreshSessionResponse)
	err := c.cc.Invoke(ctx, TherapistService_UserRefreshSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) UserLogout(ctx context.Context, in *UserLogoutRequest, opts ...grpc.CallOption) (*UserLogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserLogoutResponse)
	err := c.cc.Invoke(ctx, TherapistService_UserLogout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) SearchTherapists(ctx context.Context, in *SearchTherapistsRequest, opts ...grpc.CallOption) (*SearchTherapistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchTherapistsResponse)
	err := c.cc.Invoke(ctx, TherapistService_SearchTherapists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) GetRecommendedTherapists(ctx context.Context, in *GetRecommendedTherapistsRequest, opts ...grpc.CallOption) (*GetRecommendedTherapistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecommendedTherapistsResponse)
	err := c.cc.Invoke(ctx, TherapistService_GetRecommendedTherapists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) CreateBlog(ctx context.Context, in *CreateBlogRequest, opts ...grpc.CallOption) (*CreateBlogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBlogResponse)
	err := c.cc.Invoke(ctx, TherapistService_CreateBlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) UpdateBlog(ctx context.Context, in *UpdateBlogRequest, opts ...grpc.CallOption) (*UpdateBlogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBlogResponse)
	err := c.cc.Invoke(ctx, TherapistService_UpdateBlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) PublishBlog(ctx context.Context, in *PublishBlogRequest, opts ...grpc.CallOption) (*PublishBlogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishBlogResponse)
	err := c.cc.Invoke(ctx, TherapistService_PublishBlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) DeleteBlog(ctx context.Context, in *DeleteBlogRequest, opts ...grpc.CallOption) (*DeleteBlogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBlogResponse)
	err := c.cc.Invoke(ctx, TherapistService_DeleteBlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) GetBlog(ctx context.Context, in *GetBlogRequest, opts ...grpc.CallOption) (*GetBlogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlogResponse)
	err := c.cc.Invoke(ctx, TherapistService_GetBlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) ListBlogs(ctx context.Context, in *ListBlogsRequest, opts ...grpc.CallOption) (*ListBlogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlogsResponse)
	err := c.cc.Invoke(ctx, TherapistService_ListBlogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) ListMyBlogs(ctx context.Context, in *ListMyBlogsRequest, opts ...grpc.CallOption) (*ListMyBlogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyBlogsResponse)
	err := c.cc.Invoke(ctx, TherapistService_ListMyBlogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) ToggleLikeBlog(ctx context.Context, in *ToggleLikeBlogRequest, opts ...grpc.CallOption) (*ToggleLikeBlogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToggleLikeBlogResponse)
	err := c.cc.Invoke(ctx, TherapistService_ToggleLikeBlog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *therapistServiceClient) UploadBlogImage(ctx context.Context, in *UploadBlogImageRequest, opts ...grpc.CallOption) (*UploadBlogImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadBlogImageResponse)
	err := c.cc.Invoke(ctx, TherapistService_UploadBlogImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TherapistServiceServer is the server API for TherapistService service.
// All implementations must embed UnimplementedTherapistServiceServer
// for forward compatibility.
type TherapistServiceServer interface {
	// ── Therapist auth / onboarding ───────────────────────────────────────────
	// Called after Supabase auth. Upserts the therapist and returns their state + tokens.
	AuthCallback(context.Context, *AuthCallbackRequest) (*AuthCallbackResponse, error)
	// Returns the current state for an already-authenticated therapist.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// Saves the full onboarding form (sets status = pending).
	CompleteOnboarding(context.Context, *CompleteOnboardingRequest) (*CompleteOnboardingResponse, error)
	// Admin: approve a therapist (generates referral ID, sets status = verified).
	ApproveTherapist(context.Context, *ApproveTherapistRequest) (*ApproveTherapistResponse, error)
	// Admin: reject a therapist with an optional reason.
	RejectTherapist(context.Context, *RejectTherapistRequest) (*RejectTherapistResponse, error)
	// Upload a file (profile photo, degree certificate, government ID).
	// Returns a URL string. Max 3 MB enforced server-side.
	UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error)
	// Exchange a valid refresh token for a new access + refresh token pair.
	RefreshSession(context.Context, *RefreshSessionRequest) (*RefreshSessionResponse, error)
	// Invalidate the refresh token (log out this device).
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	// ── User (client/patient) auth / onboarding ───────────────────────────────
	// Called after Supabase auth for users (clients looking for a therapist).
	UserAuthCallback(context.Context, *UserAuthCallbackRequest) (*UserAuthCallbackResponse, error)
	// Saves the user onboarding form.
	CompleteUserOnboarding(context.Context, *CompleteUserOnboardingRequest) (*CompleteUserOnboardingResponse, error)
	// Fetch the authenticated user's own profile.
	GetUserProfile(context.Context, *GetUserProfileRequest) (*GetUserProfileResponse, error)
	// Exchange a user refresh token for a new access + refresh token pair.
	UserRefreshSession(context.Context, *UserRefreshSessionRequest) (*UserRefreshSessionResponse, error)
	// Invalidate the user refresh token (log out this device).
	UserLogout(context.Context, *UserLogoutRequest) (*UserLogoutResponse, error)
	// ── Discovery (user-facing) ───────────────────────────────────────────────
	// Full-text search across verified therapists.
	SearchTherapists(context.Context, *SearchTherapistsRequest) (*SearchTherapistsResponse, error)
	// Location + rating-based recommendations for a user.
	GetRecommendedTherapists(context.Context, *GetRecommendedTherapistsRequest) (*GetRecommendedTherapistsResponse, error)
	// ── Blog ──────────────────────────────────────────────────────────────────
	// Create a draft blog (verified therapists only).
	CreateBlog(context.Context, *CreateBlogRequest) (*CreateBlogResponse, error)
	// Update a draft blog (owner only).
	UpdateBlog(context.Context, *UpdateBlogRequest) (*UpdateBlogResponse, error)
	// Publish a draft blog (owner only).
	PublishBlog(context.Context, *PublishBlogRequest) (*PublishBlogResponse, error)
	// Delete a blog (owner only).
	DeleteBlog(context.Context, *DeleteBlogRequest) (*DeleteBlogResponse, error)
	// Fetch a single blog; increments view count for published blogs.
	GetBlog(context.Context, *GetBlogRequest) (*GetBlogResponse, error)
	// List published blogs (optionally filtered by therapist).
	ListBlogs(context.Context, *ListBlogsRequest) (*ListBlogsResponse, error)
	// List all blogs (draft + published) for the authenticated therapist.
	ListMyBlogs(context.Context, *ListMyBlogsRequest) (*ListMyBlogsResponse, error)
	// Toggle like on a published blog.
	ToggleLikeBlog(context.Context, *ToggleLikeBlogRequest) (*ToggleLikeBlogResponse, error)
	// Upload a single inline blog image (max 2 MB).
	UploadBlogImage(context.Context, *UploadBlogImageRequest) (*UploadBlogImageResponse, error)
	mustEmbedUnimplementedTherapistServiceServer()
}

// UnimplementedTherapistServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTherapistServiceServer struct{}

func (UnimplementedTherapistServiceServer) AuthCallback(context.Context, *AuthCallbackRequest) (*AuthCallbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthCallback not implemented")
}
func (UnimplementedTherapistServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedTherapistServiceServer) CompleteOnboarding(context.Context, *CompleteOnboardingRequest) (*CompleteOnboardingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteOnboarding not implemented")
}
func (UnimplementedTherapistServiceServer) ApproveTherapist(context.Context, *ApproveTherapistRequest) (*ApproveTherapistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveTherapist not implemented")
}
func (UnimplementedTherapistServiceServer) RejectTherapist(context.Context, *RejectTherapistRequest) (*RejectTherapistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectTherapist not implemented")
}
func (UnimplementedTherapistServiceServer) UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedTherapistServiceServer) RefreshSession(context.Context, *RefreshSessionRequest) (*RefreshSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshSession not implemented")
}
func (UnimplementedTherapistServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedTherapistServiceServer) UserAuthCallback(context.Context, *UserAuthCallbackRequest) (*UserAuthCallbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UserAuthCallback not implemented")
}
func (UnimplementedTherapistServiceServer) CompleteUserOnboarding(context.Context, *CompleteUserOnboardingRequest) (*CompleteUserOnboardingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteUserOnboarding not implemented")
}
func (UnimplementedTherapistServiceServer) GetUserProfile(context.Context, *GetUserProfileRequest) (*GetUserProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProfile not implemented")
}
func (UnimplementedTherapistServiceServer) UserRefreshSession(context.Context, *UserRefreshSessionRequest) (*UserRefreshSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UserRefreshSession not implemented")
}
func (UnimplementedTherapistServiceServer) UserLogout(context.Context, *UserLogoutRequest) (*UserLogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UserLogout not implemented")
}
func (UnimplementedTherapistServiceServer) SearchTherapists(context.Context, *SearchTherapistsRequest) (*SearchTherapistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchTherapists not implemented")
}
func (UnimplementedTherapistServiceServer) GetRecommendedTherapists(context.Context, *GetRecommendedTherapistsRequest) (*GetRecommendedTherapistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecommendedTherapists not implemented")
}
func (UnimplementedTherapistServiceServer) CreateBlog(context.Context, *CreateBlogRequest) (*CreateBlogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBlog not implemented")
}
func (UnimplementedTherapistServiceServer) UpdateBlog(context.Context, *UpdateBlogRequest) (*UpdateBlogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBlog not implemented")
}
func (UnimplementedTherapistServiceServer) PublishBlog(context.Context, *PublishBlogRequest) (*PublishBlogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishBlog not implemented")
}
func (UnimplementedTherapistServiceServer) DeleteBlog(context.Context, *DeleteBlogRequest) (*DeleteBlogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBlog not implemented")
}
func (UnimplementedTherapistServiceServer) GetBlog(context.Context, *GetBlogRequest) (*GetBlogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlog not implemented")
}
func (UnimplementedTherapistServiceServer) ListBlogs(context.Context, *ListBlogsRequest) (*ListBlogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBlogs not implemented")
}
func (UnimplementedTherapistServiceServer) ListMyBlogs(context.Context, *ListMyBlogsRequest) (*ListMyBlogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyBlogs not implemented")
}
func (UnimplementedTherapistServiceServer) ToggleLikeBlog(context.Context, *ToggleLikeBlogRequest) (*ToggleLikeBlogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleLikeBlog not implemented")
}
func (UnimplementedTherapistServiceServer) UploadBlogImage(context.Context, *UploadBlogImageRequest) (*UploadBlogImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadBlogImage not implemented")
}
func (UnimplementedTherapistServiceServer) mustEmbedUnimplementedTherapistServiceServer() {}
func (UnimplementedTherapistServiceServer) testEmbeddedByValue()                          {}

// UnsafeTherapistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TherapistServiceServer will
// result in compilation errors.
type UnsafeTherapistServiceServer interface {
	mustEmbedUnimplementedTherapistServiceServer()
}

func RegisterTherapistServiceServer(s grpc.ServiceRegistrar, srv TherapistServiceServer) {
	// If the following call panics, it indicates UnimplementedTherapistServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TherapistService_ServiceDesc, srv)
}

func _TherapistService_AuthCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).AuthCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_AuthCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).AuthCallback(ctx, req.(*AuthCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_CompleteOnboarding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteOnboardingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).CompleteOnboarding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_CompleteOnboarding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).CompleteOnboarding(ctx, req.(*CompleteOnboardingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_ApproveTherapist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveTherapistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).ApproveTherapist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_ApproveTherapist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).ApproveTherapist(ctx, req.(*ApproveTherapistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_RejectTherapist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectTherapistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).RejectTherapist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_RejectTherapist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).RejectTherapist(ctx, req.(*RejectTherapistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_UploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).UploadFile(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_RefreshSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).RefreshSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_RefreshSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).RefreshSession(ctx, req.(*RefreshSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_UserAuthCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAuthCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).UserAuthCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_UserAuthCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).UserAuthCallback(ctx, req.(*UserAuthCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_CompleteUserOnboarding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteUserOnboardingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).CompleteUserOnboarding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_CompleteUserOnboarding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).CompleteUserOnboarding(ctx, req.(*CompleteUserOnboardingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_GetUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).GetUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_GetUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).GetUserProfile(ctx, req.(*GetUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_UserRefreshSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRefreshSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).UserRefreshSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_UserRefreshSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).UserRefreshSession(ctx, req.(*UserRefreshSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_UserLogout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).UserLogout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_UserLogout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).UserLogout(ctx, req.(*UserLogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_SearchTherapists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTherapistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).SearchTherapists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_SearchTherapists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).SearchTherapists(ctx, req.(*SearchTherapistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_GetRecommendedTherapists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendedTherapistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).GetRecommendedTherapists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_GetRecommendedTherapists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).GetRecommendedTherapists(ctx, req.(*GetRecommendedTherapistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_CreateBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).CreateBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_CreateBlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).CreateBlog(ctx, req.(*CreateBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_UpdateBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).UpdateBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_UpdateBlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).UpdateBlog(ctx, req.(*UpdateBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_PublishBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).PublishBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_PublishBlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).PublishBlog(ctx, req.(*PublishBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_DeleteBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).DeleteBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_DeleteBlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).DeleteBlog(ctx, req.(*DeleteBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_GetBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).GetBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_GetBlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).GetBlog(ctx, req.(*GetBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_ListBlogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).ListBlogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_ListBlogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).ListBlogs(ctx, req.(*ListBlogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_ListMyBlogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyBlogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).ListMyBlogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_ListMyBlogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).ListMyBlogs(ctx, req.(*ListMyBlogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_ToggleLikeBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleLikeBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).ToggleLikeBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_ToggleLikeBlog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).ToggleLikeBlog(ctx, req.(*ToggleLikeBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TherapistService_UploadBlogImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadBlogImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TherapistServiceServer).UploadBlogImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TherapistService_UploadBlogImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TherapistServiceServer).UploadBlogImage(ctx, req.(*UploadBlogImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TherapistService_ServiceDesc is the grpc.ServiceDesc for TherapistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TherapistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "therapist.TherapistService",
	HandlerType: (*TherapistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthCallback",
			Handler:    _TherapistService_AuthCallback_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _TherapistService_GetStatus_Handler,
		},
		{
			MethodName: "CompleteOnboarding",
			Handler:    _TherapistService_CompleteOnboarding_Handler,
		},
		{
			MethodName: "ApproveTherapist",
			Handler:    _TherapistService_ApproveTherapist_Handler,
		},
		{
			MethodName: "RejectTherapist",
			Handler:    _TherapistService_RejectTherapist_Handler,
		},
		{
			MethodName: "UploadFile",
			Handler:    _TherapistService_UploadFile_Handler,
		},
		{
			MethodName: "RefreshSession",
			Handler:    _TherapistService_RefreshSession_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _TherapistService_Logout_Handler,
		},
		{
			MethodName: "UserAuthCallback",
			Handler:    _TherapistService_UserAuthCallback_Handler,
		},
		{
			MethodName: "CompleteUserOnboarding",
			Handler:    _TherapistService_CompleteUserOnboarding_Handler,
		},
		{
			MethodName: "GetUserProfile",
			Handler:    _TherapistService_GetUserProfile_Handler,
		},
		{
			MethodName: "UserRefreshSession",
			Handler:    _TherapistService_UserRefreshSession_Handler,
		},
		{
			MethodName: "UserLogout",
			Handler:    _TherapistService_UserLogout_Handler,
		},
		{
			MethodName: "SearchTherapists",
			Handler:    _TherapistService_SearchTherapists_Handler,
		},
		{
			MethodName: "GetRecommendedTherapists",
			Handler:    _TherapistService_GetRecommendedTherapists_Handler,
		},
		{
			MethodName: "CreateBlog",
			Handler:    _TherapistService_CreateBlog_Handler,
		},
		{
			MethodName: "UpdateBlog",
			Handler:    _TherapistService_UpdateBlog_Handler,
		},
		{
			MethodName: "PublishBlog",
			Handler:    _TherapistService_PublishBlog_Handler,
		},
		{
			MethodName: "DeleteBlog",
			Handler:    _TherapistService_DeleteBlog_Handler,
		},
		{
			MethodName: "GetBlog",
			Handler:    _TherapistService_GetBlog_Handler,
		},
		{
			MethodName: "ListBlogs",
			Handler:    _TherapistService_ListBlogs_Handler,
		},
		{
			MethodName: "ListMyBlogs",
			Handler:    _TherapistService_ListMyBlogs_Handler,
		},
		{
			MethodName: "ToggleLikeBlog",
			Handler:    _TherapistService_ToggleLikeBlog_Handler,
		},
		{
			MethodName: "UploadBlogImage",
			Handler:    _TherapistService_UploadBlogImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/therapist.proto",
}
